var ig_a=true,ig_b=null,ig_c=false;function ig_aa(a,b){if(!a.className)return ig_c;for(var c=a.className.split(" "),d=[],e=ig_c,f=0;f<c.length;++f)if(c[f]!=b)d.push(c[f]);else e=ig_a;a.className=d.join(" ");return e};function ig_d(a){var b=a||document.location.href,c,d=b.indexOf("?");if(d==-1)return"";var e=b.indexOf("#");c=e==-1?b.substr(d+1):b.substr(d+1,e-d-1)+"&"+b.substr(e+1);return c.split("&")}function _esc(a){return window.encodeURIComponent?encodeURIComponent(a):escape(a)}function _unesc(a){return window.decodeURIComponent?decodeURIComponent(a):unescape(a)}
function _argsUrl(a){for(var b={},c=ig_d(a),d=0;d<c.length;d++){var e=c[d].indexOf("=");if(!(e==-1)){var f=c[d].substring(0,e),g=c[d].substring(e+1);g=g.replace(/\+/g," ");b[f]=_unesc(g)}}return b};function ig_e(a,b){var c=function(){};c.prototype=a.prototype;b.prototype=new c}function _gel(a){return document.getElementById(a)}function _gelstn(a,b){var c=b||document;if(a=="*"&&c.all)return c.all;return c.getElementsByTagName?c.getElementsByTagName(a):[]}function _gelsbyregex(a,b,c){for(var d=_gelstn(a,c),e=[],f=0,g;g=d[f];f++)b.test(g.id)&&e.push(g);return e}function _uc(a){return a.toUpperCase()}function _trim(a){return a.replace(/^\s*|\s*$/g,"")}
function _jesc(a){return a.replace(/\\/g,"\\\\").replace(/'/g,"\\'").replace(/"/g,'\\"')}function _toggle(a){if(a)if(a.style.display==""||a.style.display=="block")a.style.display="none";else if(a.style.display=="none")a.style.display="block"}function _hesc(a){return a.replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}function _striptags(a){return a.replace(/<\/?[^>]+>/gi,"")}function _ig_gmid_(a){return a.split("_")[2]}var ig_ba=0;
function _uid(){return"obj"+ig_ba++}function _min(a,b){return a<b?a:b}function _max(a,b){return a>b?a:b}function _IG_LoadScript(a,b){_sendx(a,function(c){window.eval(c);eval(b)})}function _IG_LoadScriptXDomain(a,b,c){var d=document.createElement("script");d.src=a;_gelstn("head")[0].appendChild(d);function e(){eval(b)?c():setTimeout(function(){e()},100)}b&&e()}
function _IG_LoadCss(a){var b=_gelstn("head")[0];if(!b)throw new Error("Document is missing <head> element.  Failed to load CSS.");var c=document.createElement("style");c.type="text/css";if(c.styleSheet)c.styleSheet.cssText=a;else c.appendChild(document.createTextNode(a));b.insertBefore(c,b.firstChild)}function _log(a){var b="/ig/log?msg="+_esc(a);_sendx(b)}
function _sendx(a,b,c,d){var e=ig_f();e.open(d?"POST":"GET",a,ig_a);if(b)e.onreadystatechange=function(){if(e.readyState==4)b(c&&e.responseXML?e.responseXML:e.responseText)};e.send(d||ig_b)}function _uhc(a,b,c){var d="m_"+a+"_"+b,e=_gel(d);if(!e){e=document.createElement("INPUT");e.type="hidden";e.disabled=ig_a;e.name=d;_gel("m_"+a+"_form").appendChild(e)}e.value=c;e.disabled=ig_c}
function ig_f(){var a=ig_b;if(window.ActiveXObject)(a=new ActiveXObject("Msxml2.XMLHTTP"))||(a=new ActiveXObject("Microsoft.XMLHTTP"));else if(window.XMLHttpRequest)a=new XMLHttpRequest;return a}var _et="",_brand="",_bmod="",_source="",_ae="",_pid="",_authpath="",_prefid="",_setp_url="/ig/setp",_old_html=ig_a,_use_old_feed_styles=ig_a,ig_g=ig_b,ig_h=ig_b;function ig_i(a,b,c){var d=document.createElement("input");d.type="hidden";d.name=b;d.value=c;a.appendChild(d)}
function _args(){return _argsUrl(document.location.href)}function _IG_isIE(){return/msie/i.test(navigator.userAgent)}function _qs(a){var b={pid:1,host:1,gl:1,hl:1,enable_flag:1},c=a||_args(),d="?";for(var e in c)if(b[e])d+=e+"="+_esc(c[e])+"&";return d}var ig_ca=/^([^?#]+)(?:\?([^#]*))?(#.*)?/;function ig_j(a,b){var c=ig_ca.exec(a),d=[c[1],"?",c[2]];d.push(c[2]?"&":"",b.join("&"),c[3]);return d.join("")}
function ig_k(a){var b={url:document.location,et:_et,brand:_brand,bmod:_bmod,source:_source,ae:_ae,pid:_pid,ap:_authpath,prefid:_prefid};for(var c in b)ig_i(a,c,b[c])}function _submit_form(a,b){a.action=_setp_url+_qs()+b;a.method="get";ig_k(a);a.submit()}function _fsetp(a,b,c){a.action=_setp_url;a.method="get";ig_k(a);ig_i(a,"m_"+b+"_t",c);var d=_args(),e=d.host,f=d.hl;e&&ig_i(a,"host",e);f&&ig_i(a,"hl",f);return ig_a}var ig_l=[],ig_m=ig_c;
function ig_da(a){for(var b=[],c=0;c<a.length;++c)if(!(a[c].length!=2)){var d=a[c][0],e=a[c][1];e!=ig_b&&e!=""&&b.push(d+"="+e)}return b.join("&")}function ig_n(){return ig_da([["et",_et],["pid",_pid],["ap",_authpath],["brand",_brand],["bmod",_bmod],["source",_source],["ae",_ae],["prefid",_prefid]])}function ig_o(){if(ig_l.length==0)ig_m=ig_c;else{ig_m=ig_a;var a=_setp_url+_qs()+ig_n(),b=ig_l.shift(),c=a.length+b.length>=1800;if(c)_sendx(a,ig_p,ig_c,b);else{a+="&"+b;_sendx(a,ig_p,ig_c,ig_b)}}}
function ig_p(){_IG_TriggerDelayedEvent("xsetpdone");ig_o()}function _xsetp(a){ig_l.push(a);ig_m||ig_o()}function _xsetp_is_done(){return ig_l.length==0&&ig_m==ig_c}function _dlsetp(a,b){b||(b=_esc(document.location));document.location=_setp_url+_qs()+ig_n()+"&url="+b+"&"+a}function _removeTabParam(a){return a.replace(/(\?.*\b)(t\=[^&#]*[&#]?)/g,"$1")}function _select_tab(a,b){var c=b||"/ig";window.location.href=c+_qs()+"t="+a}
function _select_tab_and_log(a,b){_sendx("/ig/ui?xp=v2&action=selectTab&t="+a);_select_tab(a,b)}function _select_gadget_and_log(a,b){_sendx("/ig/ui?xp=v2&action=maximizeMod&from=selectMod&mid="+b);window.location.href="/ig"+_qs()+"t="+a+"&g="+b}function _ssbc(a,b,c){for(var d=_gelstn("*"),e=0,f;f=d[e];e++)if(f.className==a)f.style[b]=c}function ig_ea(a){for(var b=_gelstn("*"),c=0,d;d=b[c];c++)for(var e=0;e<a.length;e++)if(d.className==a[e][0])d.style[a[e][1]]=a[e][2]}
function _findPos(a){for(var b=0,c=0;a!=ig_b;){b+=a.offsetLeft;c+=a.offsetTop;a=a.offsetParent}return[b,c]}function _getGadgetContainer(a){var b=_gel("m_"+a+"_b");if(!b){b=_gel("remote_"+a);if(!b)b=document.body}return b}function _appendMaxAgeParameter(a,b){var c=/[?&]$/.test(a);return a+(c?"":"&")+"max_age="+b+(c?"&":"")}function ig_q(a){var b=window;if(a!="")for(var c=a.split(".");c.length;){var d=c.shift();if(typeof b[d]!="object")b[d]={};b=b[d]}return b}
(function(){function a(c,d){for(var e=ig_q(c),f=0;f<d.length;f+=2)e[d[f]]=d[f+1]}function b(c,d,e,f,g){if(f)for(var h=0;h<f.length;h+=2)e.prototype[f[h]]=f[h+1];if(g)for(h=0;h<g.length;h+=2)e[g[h]]=g[h+1];a(c,[d,e])}a("",["_exportSymbols",a]);a("",["_exportClass",b]);a("google.gadgets.Util",["args",_args]);a("",["addParamPairsToUrl",ig_j,"xmlhttp",ig_f])})();var ig_r=["_IG_DD_open","_IG_hoverHeader","_IG_hoverModule"],ig_s=["_IG_DD_create","_IG_DD_init","_IG_initDrag","_IG_maximize_persistent_module","_IG_PushHistory","_IG_PU_MakeDialogButton"],ig_t=ig_c,ig_u=ig_c;if(!window.FLAG_isInSplitJS)window.FLAG_isInSplitJS=ig_c;var ig_v=[];function ig_fa(){for(var a=0;a<ig_r.length;a++)_IG_ignoreFunction(ig_r[a]);for(a=0;a<ig_s.length;a++)_IG_deferFunction(ig_s[a])}
function _IG_deferFunction(a){if(window.FLAG_isInSplitJS){var b=window,c=a.lastIndexOf(".");if(c>=0){b=ig_q(a.substring(0,c));a=a.substring(c+1)}if(b[a])throw new Error(a+" is already defined.");b[a]=ig_ga(a)}}function _IG_ignoreFunction(a){if(window.FLAG_isInSplitJS){var b=window,c=a.lastIndexOf(".");if(c>=0){b=ig_q(a.substring(0,c));a=a.substring(c+1)}b[a]=function(){}}}
function ig_ga(a){var b=function(){for(var c=[],d=0;d<arguments.length;d++)c.push(arguments[d]);ig_v.push([a,this,c])};b.isDeferredFunction=ig_a;return b}function ig_w(){if(!(ig_v.length==0)){var a=ig_v.shift(),b=a[0],c=a[1],d=a[2];try{var e=b instanceof Function?b:window[b];e.apply(c,d)}catch(f){}if(ig_v.length>0)setTimeout(ig_w,0);else{ig_u=ig_a;ig_ha()}}}
function ig_ia(){for(var a=[],b=0;b<ig_v.length;b++){var c=ig_v[b][0];if(!(c instanceof Function))if(window[c].isDeferredFunction){a.push(c);ig_v.splice(b,1);b--}}setTimeout(ig_w,0);if(a.length>0)throw new Error("The following functions were not found in the post load file: "+a.join(", "));}function ig_ha(){for(var a=_gelstn("*"),b=0;b<a.length;b++){var c=a[b];c.className&&c.className.split&&ig_aa(c,"disabled")}}
function _IG_loadPostloadJS(a,b){var c=ig_ja(b);_IG_AddEventHandler(a,c);setTimeout(c,10000)}function ig_ja(a){return function(){if(!ig_t){_IG_LoadScriptXDomain(a,"window._IG_noMaxSupportTransitionStrategy",ig_ia);ig_t=ig_a}}}function _IG_callPostLoad(a){ig_u||!window.FLAG_isInSplitJS?a():ig_v.push([a,ig_b,[]])}ig_fa();function _edit(a,b){var c=function(){b&&b();_sendx("/ig/ui?action=editsettings&m="+a);ig_x("edit","m_"+a)};ig_y(a,ig_c);var d=ig_z[a];if(d){d();c()}else _IG_LL_load("m_"+a+"_editbox",{mid:a},function(){_gel("m_"+a).className="modbox_e";c()});return ig_c}function _osedit(a){_log("social_options:"+a);_gel("m_"+a).className="modbox_e";ig_y(a,ig_a)}function ig_y(a,b){var c=_gel("gadget_prefs_"+a),d=_gel("acl_options_"+a);if(c&&d){c.style.display=b?"none":"";d.style.display=b?"block":"none"}}
var ig_z={};function _IG_AddCustomEditHandler(a,b){ig_z[a]=b}function _cedit(a){_gel("m_"+a).className="modbox";var b=_gel("m_"+a+"_form");if(b){b.reset();_sendx("/ig/ui?action=canceledit&m="+a);ig_x("canceledit","m_"+a);return ig_c}}function _confirmDel(a,b,c,d){var e=_striptags(_gel("m_"+a+"_title").innerHTML);d=d.replace(/MODULE_TITLE/,'"'+e+'"');confirm(d)&&_del(a,b,c)}
function _get_module_title(a){if(typeof a=="object")a=a.id.replace("m_","");else if(typeof a=="string")a=a.replace("m_","");var b=_gel("m_"+a+"_title");return b?_striptags(b.innerHTML):""}
function _get_all_modules(){for(var a=ig_ka(),b=[],c=/^m_[0-9]+$/,d=0;d<a.length;d++){b[d]=[];for(var e=b[d],f=0;f<a[d].childNodes.length;f++){var g=a[d].childNodes[f];g.tagName=="DIV"&&g.style.display!="none"&&g.id&&c.test(g.id)&&e.push(g)}}if(window.gadgets&&window.gadgets.views&&window.gadgets.views.ViewManager&&window.gadgets.views.ViewManager.getCurrentMaxId){var h=window.gadgets.views.ViewManager.getCurrentMaxId();h&&b.length>0&&h&&b[0].unshift(_gel("m_"+h))}return b}
function ig_ka(){for(var a=_gelsbyregex("DIV",/^c_[0-9]+$/),b=[],c=0;c<a.length;c++)a[c].style.display!="none"&&b.push(a[c]);return b}var ig_A={},ig_B={};function _place(a,b){var c=ig_B[a];if(c)c(b);else{ig_A[a]||(ig_A[a]=[]);ig_A[a].push(b)}}function _register_place(a,b){ig_B[a]=b;var c=ig_A[a];if(c){for(var d=0;d<c.length;d++)b(c[d]);ig_A[a]=ig_b}}var ig_C=ig_c;function _del_is_done(){return _xsetp_is_done()&&ig_C}
function _del(a,b,c){ig_C=ig_c;_xsetp("m_"+a+"_enab=0&m_"+a+"_t="+b);var d=_gel("undel_msg");if(d){_gel("undel_title").innerHTML="&quot;"+_get_module_title(a)+"&quot; ";d.style.display="block";var e=_gel("undo_msg");if(e)e.style.display="none";if(e=_gel("undo_restore_msg"))e.style.display="none"}var f=_gel("m_"+a);if(f)f.style.display="none";ig_g=a;ig_h=c;var g=_gel(c);if(g)g.style.display="";_mod=ig_a;ig_x("delete","m_"+a);ig_C=ig_a;return ig_c}
function _undel(){if(!(ig_g==ig_b)){var a="m_"+ig_g,b=_gel(a);if(b){b.style.display="block";_xsetp("undel")}var c=_gel("undel_msg");if(c)c.style.display="none";if(ig_h!=ig_b){var d=_gel(ig_h);if(d)d.style.display="none"}ig_h=ig_g=ig_b;ig_x("undelete",a)}}
function _zm(a,b,c){var d=_gel("m_"+a+"_b");if(d){var e=d.style.display!="none";d.style.display=e?"none":"block";var f=_gel("m_"+a+"_zippy");if(f)f.className=e?f.className.replace(/minbox/,"maxbox"):f.className.replace(/maxbox/,"minbox");var g=c?"mmz":"mz";_xsetp(g+"="+a+":"+(e?"1":"0")+"&t="+b);ig_x(e?"zip":"unzip",a)}return ig_c}var ig_la="https://www.google.com/accounts";
function _enableGS(a,b){a.action=ig_la+"/CheckCookie";a.method="get";ig_i(a,"service",b);ig_i(a,"continue",document.location);ig_i(a,"skipvpage",ig_a);return ig_a}function _reload(a,b){var c=a-(new Date).getTime();if(c>1000)setTimeout("_reload("+a+")",c);else if(b)document.location.replace(ig_ma(document.location.href,document.location.pathname));else{document.cookie="IGREL=1";document.location.replace(document.location.href.split("#")[0])}}var ig_na=/^([^?#]+)(?:\?([^#]*))?(#.*)?/;
function ig_ma(a,b){var c=ig_na.exec(a),d=c[1];if(b=="/")d+="ig";d+="?";var e=c[2];if(e)d+=e;if(!_argsUrl(a).refresh){if(e)d+="&";d+="refresh=1"}return d}function ig_x(a,b){switch(a){case "delete":case "undelete":case "edit":case "canceledit":case "zip":case "unzip":case "mazimize":case "unmaximize":_IG_TriggerDelayedModuleEvent(b,a);_IG_TriggerDelayedEvent("module"+a,b);break}}function ig_oa(a){_xsetp("pnlo="+(a?1:0))}var _uli,_pnlo,_mpnlo,_pl,_mod,_cbp=ig_c,ig_D=ig_c,_table=ig_b,_tabs=ig_b;
function _upc(){var a=[];_cbp||(a[a.length]=["medit","display",_uli?"":"none"]);a[a.length]=["panelo","display",_pnlo?"":"none"];a[a.length]=["panelc","display",_pnlo?"none":""];if(_mod){a[a.length]=["unmod","display","none"];a[a.length]=["mod","display",""]}else{a[a.length]=["mod","display","none"];a[a.length]=["unmod","display",""]}ig_ea(a);_IG_callPostLoad(_init_drag_drop)}
function _init_drag_drop(){if(_pl)if(_cbp||_uli)if(!ig_D&&!_mpnlo){_IG_TriggerCustomEvent("initdrag",_table,_tabs);ig_D=ig_a}}var ig_E=0;
function _tp(a){ig_E>0&&clearInterval(ig_E);_pnlo=a;_mod=ig_a;ig_oa(a);_upc();var b=_gel("cpnl"),c=_gel("cpnlc"),d=_gel("nhdr"),e=_gel("ehdr"),f=b.offsetWidth,g,h;if(a){g=c.offsetWidth;h="visible";e.style.display="";d.style.display="none"}else{g=1;h="hidden";e.style.display="none";d.style.display=""}b.style.overflow="hidden";var j=100,i=10,k=0;ig_E=setInterval(function(){var l=k/i,o=f+(g-f)*l;b.style.width=o+"px";k++;if(l>=1){clearInterval(ig_E);ig_E=0;b.style.width=g+"px";b.style.overflow=h}},j/
i);return ig_c}function _ts(a,b){var c=_gel(a+b),d;if(c.className=="mlist_open"){c.className="mlist_closed";d="pnlsc"}else{c.className="mlist_open";d="pnlso"}_xsetp(d+"="+_esc(b));return ig_c}function _add_m(a,b){_dlsetp(a,b)}function _add_m_confirm(a,b,c){confirm(b)&&_add_m(a,c)}function _add_f(a){_add_m("n_25="+_esc("url="+_esc(a)))}var ig_F=/^_add_m(_confirm)?\(\"[^"]+\"(, *\"[^"]+\")?\)$/,ig_G=ig_a;function _find_feed_is_done(){return ig_G}
function _find_feed(a){ig_G=ig_c;var b="acd";if(!a){var c=_gelstn("div");if(c)for(var d=0,e;e=c[d];d++)e.id&&e.id.indexOf("ps")==0&&e.className=="mlist_open"&&_ts("ps",e.id.substring(2));if(_gel("add_custom"))a=_gel("add_custom").value}if(!a||a==""){b="advdsrch";a=_gel("add_advd").value}var f=_gel("ffresults");if(f)f.style.display="none";var g=_gel("ffloading");if(g)g.style.display="block";_sendx("/ig/feeds"+_qs()+"q="+_esc(a)+"&page="+_esc(b),ig_pa);return ig_c}
function ig_pa(a){var b=_gel("ffloading");if(b)b.style.display="none";var c=_gel("ffresults");if(c)c.style.display="block";if(a.length>0&&a.charAt(0)=="<")c.innerHTML=a;else a.match(ig_F)!=ig_b?eval(a):eval(a);ig_G=ig_a}function _add_remote_module(a,b,c){_sendx("/ig/feeds"+_qs()+"module=1&q="+_esc(a),function(d){b();ig_qa(d,c)});return ig_c}
function ig_qa(a,b){var c=/_add_m_confirm\((\"[^"]+\"),\s*(\"[^"]+\")(,\s*\"[^"]+\")?\)/,d=/^alert\(\"[^"]+\"\)$/;if(a.match(ig_F)!=ig_b||a.match(d)!=ig_b){if(b)a=a.replace(c,"_add_m($1$3)");eval(a)}}
function _ListApp(a,b,c){this.items=a;this.deleted=[];this.item_constructor=b;this.module_id=c;this.app_name="m_"+c+"_App";this.display_area=_gel("m_"+c+"_disp");this.sort_on_refresh=ig_a;this.value_input_field=_gel("m_"+c+"_val");this.name_input_field=_gel("m_"+c+"_name");if(!this.name_input_field)this.name_input_field=this.value_input_field;if(this.name_input_field){this.default_name=this.name_input_field.value;this.default_value=this.value_input_field.value}this.prev_items=[].concat(this.items)}
_ListApp.prototype.reset=function(){this.items=[].concat(this.prev_items);this.deleted=[];this.refresh()};_ListApp.prototype.sort=function(a,b){return a.F(b)};
_ListApp.prototype.Ya=function(){var a="";if(_old_html)a="<table cellspacing=0 cellpadding=0 border=0>";for(var b="",c=this.items,d=0;d<c.length;d++)if(c[d]){a+=_old_html?"<tr><td nowrap><font size=-1>"+c[d].L()+'</font></td><td><a href="#" onclick="'+this.app_name+"._del("+d+');return false"><img src="/ig/images/x.gif" width=16 height=13 border=0></a></td></tr>':'<a href="#" onclick="'+this.app_name+"._del("+d+');return false" class="delbox listdelbox"></a>'+c[d].L()+'<div class="c"></div>';if(parseInt(c[d]._uid,
10)<0)b+=c[d].v(d)}else{this.items.splice(d,1);d--}var e=this.deleted,f="";for(d=0;d<e.length;d++)if(parseInt(e[d]._uid,10)>=0)f+=","+e[d]._uid;a+=this.qa(b,f);return a};_ListApp.prototype.qa=function(a,b){var c="<input type=hidden name=m_"+this.module_id+'_del value="'+b+'"><input type=hidden name=m_'+this.module_id+'_add value="'+a+'">';if(_old_html)c="</table><input type=hidden name=m_"+this.module_id+'_del value="'+b+'"><input type=hidden name=m_'+this.module_id+'_add value="'+a+'">';return c};
_ListApp.prototype.refresh=function(){this.sort_on_refresh&&this.items.sort(this.sort);this.display_area.innerHTML="<font size=-1>"+this.Ya()+"</font>"};_ListApp.prototype.add=function(a,b){a||(a=_trim(this.name_input_field.value));b||(b=_trim(this.value_input_field.value));var c=new this.item_constructor(a,b,-1);if(c.I()){this.items[this.items.length]=c;this.refresh();this.name_input_field.value=this.default_name;this.value_input_field.value=this.default_value}};
_ListApp.prototype._del=function(a){this.deleted[this.deleted.length]=this.items[a];this.items.splice(a,1);this.refresh()};
function _PrefListApp(a,b,c,d,e){var f=typeof c=="string"?[]:c,g=new _ListApp(f,d,e);for(var h in g)this[h]=g[h];typeof c=="string"&&this.Xa(c);this.prefidx=a;this.prefname=b;this.app_name="m_"+e+"_"+a+"_App";this.display_area=_gel("m_"+e+"_"+a+"_disp");this.name_input_field=this.value_input_field=_gel("m_"+e+"_"+a+"_val");this.default_value=this.default_name="";this.qa=_PrefListApp_get_tail}
function _PrefListApp_get_tail(){var a="</table>";_gel("m_"+this.module_id+"_"+this.prefidx).value=this.ab();return a}_PrefListApp.prototype.Xa=function(a){if(!(a.length==0)){for(var b=_IG_Prefs._strToArray(a),c=[],d=0;d<b.length;d++){var e=new this.item_constructor(b[d],b[d],-1);c[c.length]=e}this.items=c;this.prev_items=[].concat(c)}};_PrefListApp.prototype.ab=function(){for(var a=[],b=0;b<this.items.length;b++)a[a.length]=this.items[b]._v;return _IG_Prefs._arrayToStr(a)};
function _ListItem(a,b,c){this._n=a;this._v=b;this._uid=c}_ListItem.prototype.I=function(){return this._n!=""};_ListItem.prototype.F=function(){return 0};_ListItem.prototype.L=function(){return _hesc(this._n)};_ListItem.prototype.v=function(){return"&"+_esc(this._n)+"="+_esc(this._v)};function _BMListItem(a,b,c){_ListItem.call(this,a,b,c)}ig_e(_ListItem,_BMListItem);_BMListItem.prototype.I=function(){return _ListItem.prototype.I.call(this)&&this._n!="http://"};
_BMListItem.prototype.R=function(){if(this._v)return this._v;else{var a=this._n;if(a.indexOf("http://")==0)a=a.substring(7);if(a.indexOf("www.")==0)a=a.substring(4);return a}};_BMListItem.prototype.L=function(){return'<a href="'+this._n+'" target=bmwindow>'+_hesc(this.R())+"</a>"};_BMListItem.prototype.v=function(a){return"&b"+a+"="+_esc(this._n)+"&t"+a+"="+_esc(this._v)};_BMListItem.prototype.F=function(a){var b=_uc(this.R()),c=_uc(a.R());if(b==c)return 0;return b<c?-1:1};
function _WthrListItem(a,b,c){_ListItem.call(this,a,b,c)}ig_e(_ListItem,_WthrListItem);_WthrListItem.prototype.v=function(){var a="&"+_esc(this._n);if(this._v)a+="="+_esc(this._v);return a};function _FListItem(a,b,c,d){_ListItem.call(this,a,b,c);this._s=d||0}ig_e(_ListItem,_FListItem);_FListItem.prototype.v=function(){return"&"+_esc(this._n)};_FListItem.prototype.F=function(a){var b=this;if(b._s<a._s)return-1;if(b._s>a._s)return 1;var c=_uc(b._n),d=_uc(a._n);if(c<d)return-1;if(c>d)return 1;return 0};
var ig_H={ha:0,cb:1800,ya:ig_b,xa:ig_b,aa:ig_a,M:ig_b,eb:ig_b,Ra:600,O:function(){ig_H.ha=(new Date).getTime()+ig_H.cb*1000},yb:function(){if((new Date).getTime()>ig_H.ha)window.gTalkNotifier&&window.gTalkNotifier._isAnyMoleOpen&&window.gTalkNotifier._isAnyMoleOpen()?ig_H.O():_testConnection(function(){_reload(ig_H.ha,ig_H.eb)},ig_H.O)},Aa:function(a){ig_H.O();ig_H.ya&&ig_H.ya(a)},za:function(a){ig_H.O();ig_H.xa&&ig_H.xa(a)}};
function _IG_disable_refresh_cycle(){ig_H.aa=ig_c;_IG_suspend_refresh_cycle()}function _IG_suspend_refresh_cycle(){if(ig_H.M!=ig_b){clearInterval(ig_H.M);ig_H.M=ig_b}}function _IG_restart_refresh_cycle(){!ig_H.aa||ig_H.M!=ig_b||ig_I()}
function _IG_start_refresh_cycle(a,b,c){if(ig_H.aa){ig_H.ya=document.onmousedown;ig_H.xa=document.onkeyup;ig_H.cb=a;ig_H.Ra=b;if(c)ig_H.eb=c;if(document.addEventListener){document.addEventListener("keyup",ig_H.za,ig_c);document.addEventListener("mousedown",ig_H.Aa,ig_c)}else if(document.attachEvent){document.attachEvent("onkeyup",ig_H.za);document.attachEvent("onmousedown",ig_H.Aa)}else{document.onkeyup=ig_H.za;document.onmousedown=ig_H.Aa}ig_I()}}
function ig_I(){ig_H.O();ig_H.M=setInterval(ig_H.yb,ig_H.Ra*1000)}function _testConnection(a,b,c){var d=ig_f(),e="/ig/nop?t="+(new Date).getTime();c||(c=3500);d.open("GET",e,ig_a);d.onreadystatechange=function(){if(d.readyState==4&&a)if(200<=d.status&&d.status<300||d.status==1223){b=ig_b;a()}};try{d.send(ig_b)}catch(f){}var g=function(){if(b){a=ig_b;b()}};setTimeout(g,c)}function _mailWindow(a){window.open(a,"mailwindow","width=400,height=340,left=50,top=50,scrollbars=no")}
function ig_J(a){if(!a)a=document.body;return a.scrollHeight>a.offsetHeight?a.scrollHeight:a.offsetHeight}function ig_K(){return self.pageYOffset?self.pageYOffset:document.documentElement&&document.documentElement.scrollTop?document.documentElement.scrollTop:document.body.scrollTop}function _closePromoBox(a){_toggle(_gel("promo"+a));_xsetp("gpc="+a+":-1")}_exportSymbols("",["pageHeight",ig_J,"scrollTop",ig_K]);function _IG_GetCachedUrl(a,b){var c;c=typeof b=="object"?b:{};var d=window.location.href,e="/ig/proxy?",f=/^http:\/\/[^\/]+\/ig\/ifr[?]/,g=f.exec(d);if(g||d.indexOf("http://www.google.cn/ig/china")==0){if(window.location.host!="p.gmodules.com"&&_et)e+="et="+_esc(_et)+"&"}else e="http://p.gmodules.com/ig/proxy?";if(!isNaN(c.refreshInterval)&&c.refreshInterval>=0)e=_appendMaxAgeParameter(e,c.refreshInterval);return e+"url="+_esc(a)+"&log=1"}
function _IG_GetImageUrl(a,b){return _IG_GetCachedUrl(a,b)}function _IG_GetImage(a,b){var c=document.createElement("img");c.src=_IG_GetCachedUrl(a,b);return c};function _IG_Callback(a){var b=arguments;return function(){for(var c=[],d=0;d<arguments.length;d++)c[c.length]=arguments[d];for(d=1;d<b.length;d++)c[c.length]=b[d];a.apply(ig_b,c)}}function ig_L(){var a=_IG_Callback.apply(ig_b,arguments);return function(){a()}};var ig_ra={domload:1,xsetpdone:1,moduledragstart:1,moduledragend:1,moduletitleclick:1,moduleedit:1,modulecanceledit:1,moduledelete:1,moduleundelete:1,modulezip:1,moduleunzip:1,modulemaximize:1,moduleunmaximize:1,load:1,unload:1,resize:1},ig_M={},ig_sa={dragstart:1,dragend:1,titleclick:1,edit:1,canceledit:1,"delete":1,undelete:1,zip:1,unzip:1,maximize:1,unmaximize:1};function ig_ta(a){if(a.hasOwnProperty&&a.hasOwnProperty("ig_event_hashcode_"))return a.sa;a.sa||(a.sa=++ig_N.wb);return a.sa}
function ig_ua(a){return"builtin_"+a}function ig_va(a,b){if(a.indexOf&&a.indexOf("m_")==0)a=a.substring(2);return"builtin_m"+a+"_"+b}function ig_wa(a,b){return"builtin_"+ig_N.sb(a)+"_"+b}function ig_xa(a){return"custom_"+a}function ig_ya(){for(var a in ig_N.c){for(var b=0;b<ig_N.c[a].length;b++)ig_N.c[a][b]=ig_b;if(a in ig_N.Q){var c=ig_N.Q[a],d=c[0],e=c[1],f=c[2];if(d.removeEventListener)d.removeEventListener(e,f,ig_c);else d.detachEvent&&d.detachEvent("on"+e,f);ig_N.Q[a]=ig_b}}}
function ig_za(a,b,c){for(var d=c;d<b.length;d++)a[a.length]=b[d];return a}function ig_Aa(a,b){if(a in ig_N.c)for(var c=0;c<ig_N.c[a].length;c++)if(ig_N.c[a][c]===b){ig_N.c[a][c]=ig_b;return ig_a}return ig_c}function ig_Ba(a){if(a in ig_N.c)for(var b=0;b<ig_N.c[a].length;b++)if(ig_N.c[a][b]){for(var c=[],d=1;d<arguments.length;d++)c[c.length]=arguments[d];ig_N.c[a][b].apply(this,c)}}
function ig_Ca(a,b){if(!(a in ig_N.Db))throw Error("Unsupported event type: "+a);var c=ig_N.ca(a);c in ig_N.c||(ig_N.c[c]=[]);ig_N.c[c][ig_N.c[c].length]=b;return ig_N.c[c].length}function ig_Da(a,b,c){if(!(b in ig_N.Eb))throw Error("Unsupported module event type: "+b);var d=ig_N.da(a,b);d in ig_N.c||(ig_N.c[d]=[]);ig_N.c[d][ig_N.c[d].length]=c}
function ig_Ea(a,b,c){var d=ig_N.Sa(a,b);if(!(d in ig_N.c)){ig_N.c[d]=[];var e=function(g){if(!g)g=window.event;ig_N.Y.apply(a,[d,g])};if(a.addEventListener)a.addEventListener(b,e,ig_c);else if(a.attachEvent)a.attachEvent("on"+b,e);else throw Error("Object {"+a+"} does not support DOM events.");ig_N.Q[d]=[a,b,e]}var f=ig_N.c[d].length;if(a===window&&b=="unload"&&f>0){ig_N.c[d][f]=ig_N.c[d][f-1];ig_N.c[d][f-1]=c}else if(ig_M[b])setTimeout(c,10);else ig_N.c[d][f]=c}
function ig_Fa(a,b){var c=ig_N.ba(a);c in ig_N.c||(ig_N.c[c]=[]);ig_N.c[c][ig_N.c[c].length]=b}function ig_Ga(a,b){var c=ig_N.ca(a);return ig_N.W(c,b)}function ig_Ha(a,b,c){var d=ig_N.da(a,b);return ig_N.W(d,c)}function ig_Ia(a,b,c){var d=ig_N.Sa(a,b);return ig_N.W(d,c)}function ig_Ja(a,b){var c=ig_N.ba(a);return ig_N.W(c,b)}
function ig_Ka(a){var b=a=="load"||a=="domload",c=ig_c;if(b){(c=ig_M[a])||_IG_TriggerCustomEvent(a+"_start");ig_M[a]=ig_a}var d=ig_N.J([ig_N.ca(a)],arguments,1);ig_N.Y.apply(window,d);b&&!c&&_IG_TriggerCustomEvent(a+"_end")}function ig_La(){var a=ig_N.J([],arguments,0);setTimeout(function(){ig_N.triggerEvent.apply(window,a)},0)}function ig_Ma(a,b){var c=ig_N.J([ig_N.da(a,b)],arguments,2);ig_N.Y.apply(window,c)}
function ig_Na(){var a=ig_N.J([],arguments,0);setTimeout(function(){ig_N.triggerModuleEvent.apply(window,a)},0)}function ig_Oa(a){var b=ig_N.J([ig_N.ba(a)],arguments,1);ig_N.Y.apply(window,b)}function ig_Pa(){var a=ig_N.J([],arguments,0);setTimeout(function(){ig_N.triggerCustomEvent.apply(window,a)},0)}function _IG_delayScript(a,b){var c,d=!isNaN(b)&&b||10000;function e(){clearTimeout(c);_IG_RemoveEventHandler("load",e);setTimeout(a,0)}c=setTimeout(e,d);_IG_AddEventHandler("load",e)}
var ig_N={wb:0,c:{},Q:{},Db:ig_ra,Eb:ig_sa,sb:ig_ta,ca:ig_ua,da:ig_va,Sa:ig_wa,ba:ig_xa,nb:ig_ya,J:ig_za,W:ig_Aa,Y:ig_Ba,addEventHandler:ig_Ca,addModuleEventHandler:ig_Da,addDOMEventHandler:ig_Ea,addCustomEventHandler:ig_Fa,removeEventHandler:ig_Ga,removeModuleEventHandler:ig_Ha,removeDOMEventHandler:ig_Ia,removeCustomEventHandler:ig_Ja,triggerEvent:ig_Ka,triggerModuleEvent:ig_Ma,triggerCustomEvent:ig_Oa,triggerDelayedEvent:ig_La,triggerDelayedModuleEvent:ig_Na,triggerDelayedCustomEvent:ig_Pa},_IG_AddEventHandler=
ig_N.addEventHandler,_IG_AddModuleEventHandler=ig_N.addModuleEventHandler,_IG_AddGadgetEventHandler=ig_N.addModuleEventHandler,_IG_AddDOMEventHandler=ig_N.addDOMEventHandler,_IG_AddCustomEventHandler=ig_N.addCustomEventHandler,_IG_RemoveEventHandler=ig_N.removeEventHandler,_IG_RemoveModuleEventHandler=ig_N.removeModuleEventHandler,_IG_RemoveGadgetEventHandler=ig_N.removeModuleEventHandler,_IG_RemoveDOMEventHandler=ig_N.removeDOMEventHandler,_IG_RemoveCustomEventHandler=ig_N.removeCustomEventHandler,
_IG_TriggerEvent=ig_N.triggerEvent,_IG_TriggerModuleEvent=ig_N.triggerModuleEvent,_IG_TriggerGadgetEvent=ig_N.triggerModuleEvent,_IG_TriggerCustomEvent=ig_N.triggerCustomEvent,_IG_TriggerDelayedEvent=ig_N.triggerDelayedEvent,_IG_TriggerDelayedModuleEvent=ig_N.triggerDelayedModuleEvent,_IG_TriggerDelayedGadgetEvent=ig_N.triggerDelayedModuleEvent,_IG_TriggerDelayedCustomEvent=ig_N.triggerDelayedCustomEvent;_IG_AddDOMEventHandler(window,"unload",ig_N.nb);_IG_AddDOMEventHandler(window,"load",function(){_IG_TriggerEvent("load")});
_IG_AddDOMEventHandler(window,"unload",function(){_IG_TriggerEvent("unload")});_IG_AddDOMEventHandler(window,"resize",function(){_IG_TriggerEvent("resize")});function _IG_RegisterOnloadHandler(a){_IG_AddEventHandler("domload",a)}function _IG_LoadLibraryDeferred(a,b){_IG_RegisterOnloadHandler(function(){_IG_LoadScript(a,b)})}_exportSymbols("google.gadgets.Events",["addHandler",_IG_AddEventHandler,"removeHandler",_IG_RemoveEventHandler,"addOnloadHandler",_IG_RegisterOnloadHandler]);
function _IG_RegisterMaximizeHandler(a,b){_IG_AddModuleEventHandler(a,"unmaximize",function(){b(ig_c)});_IG_AddModuleEventHandler(a,"maximize",function(){b(ig_a)})};var _currentLayout,_layoutData,_IG_Layouts={savedModulePositions:ig_b};_IG_Layouts._selectLayout=function(a){for(var b=_gel("edit_this_tab_form").edit_this_tab_selected_layout,c=0;c<b.length;c++){var d=b[c].value,e=_gel("edit_this_tab_layoutimg_"+d);if(d!=a){b[c].checked=ig_c;if(e.src.indexOf("_highlight")!=-1)e.src=e.src.substring(0,e.src.indexOf("_highlight"))+".gif"}else{b[c].checked=ig_a;if(e.src.indexOf("_highlight")==-1)e.src=e.src.substring(0,e.src.indexOf(".gif"))+"_highlight.gif"}}};
_IG_Layouts._renderLayout=function(a){if(!_IG_Layouts.isLayoutValid(a))return ig_c;for(var b=_IG_Layouts.getColumnsInOrder(),c=_layoutData[a],d=ig_c,e=0;e<b.length;e++){b[e].style.width=c.sizes[e];if(b[e].style.display!=c.display[e]){b[e].style.display=c.display[e];d=ig_a}}if((a==_currentLayout||d)&&!_IG_Layouts.rearrangeModules(a))return ig_c;return ig_a};
_IG_Layouts.rearrangeModules=function(a){if(!_IG_Layouts.isLayoutValid(a))return ig_c;var b=_IG_Layouts.getColumnsInOrder(),c=_gel("lc_opt"),d=b[_layoutData[a].visibleColumns-1];d.insertBefore(c,d.firstChild);if(_IG_Layouts.savedModulePositions!=ig_b&&a==_currentLayout){for(var e=0;e<b.length;e++)for(var f=_IG_Layouts.savedModulePositions[e],g=0;g<f.length;g++){var h=_gel(f[g]);h!=ig_b&&b[e].insertBefore(h,b[e].lastChild)}return ig_a}var j=[],i=[];for(e=0;e<b.length;e++)i.push(b[e].firstChild);var k=
ig_c;do{k=ig_c;for(e=0;e<i.length;e++){for(;i[e]!=ig_b&&i[e].id.indexOf("m_")==-1;)i[e]=i[e].nextSibling;if(i[e]!=ig_b&&i[e].id.indexOf("m_")!=-1){j.push(i[e].id);k=ig_a;i[e]=i[e].nextSibling}}}while(k);var l=0;for(g=0;g<j.length;g++){b[l].insertBefore(_gel(j[g]),b[l].lastChild);do{l++;if(l>=b.length)l=0}while(b[l].style.display=="none")}return ig_a};
_IG_Layouts._saveModulePositions=function(){var a=_IG_Layouts.getColumnsInOrder();_IG_Layouts.savedModulePositions=[];for(var b=0;b<a.length;b++){_IG_Layouts.savedModulePositions[b]=[];for(var c=_IG_Layouts.savedModulePositions[b],d=0;d<a[b].childNodes.length-1;d++){var e=a[b].childNodes[d];e.tagName=="DIV"&&e.id.indexOf("m_")!=-1&&c.push(e.id)}}};
_IG_Layouts._editTabSettingsSubmit=function(a){for(var b=_gel("edit_this_tab_form").edit_this_tab_selected_layout,c=-1,d=0;d<b.length;d++)if(b[d].checked==ig_a)c=b[d].value;var e="",f=_gel("edit_this_tab_name").value;if(_gel("tab"+a+"_view_title").innerHTML!=f&&f!=""){e+="rt_"+a+"="+_esc(f);_gel("tab"+a+"_view_title").innerHTML=_hesc(f);_gel("tab"+a+"_title").value=_hesc(f);var g=_gel("tip_tabtitle");if(g!=ig_b)g.innerHTML=_hesc(f)}if(c!=_currentLayout){e+=e==""?"":"&";e+="lt_"+a+"="+c;_currentLayout=
c;for(var h=_IG_Layouts.getColumnsInOrder(),j="",i=0;i<h.length;i++)for(var k=0;k<h[i].childNodes.length-1;k++){var l=h[i].childNodes[k];if(l.tagName=="DIV"&&l.id.indexOf("m_")!=-1){j+=j==""?"":":";j+=l.id.substring(2)+"_"+(i+1)}}e+="&mp="+_esc(j)}e!=""&&_xsetp(e);_IG_Layouts.savedModulePositions=ig_b};_IG_Layouts._editTabSettingsCancel=function(){_IG_Layouts._renderLayout(_currentLayout);_IG_Layouts.savedModulePositions=ig_b};
_IG_Layouts.getColumnsInOrder=function(){for(var a=4,b=[],c=1;c<=a;c++){var d=_gel("c_"+c);if(d==ig_b)break;b.push(d)}return b};_IG_Layouts.isLayoutValid=function(a){if(a<0||a>_layoutData.length-1)return ig_c;return ig_a};var ig_O=function(){var a=ig_c,b=[],c=ig_b,d=ig_b;function e(){if(!(c||a)){a=ig_a;_IG_LoadScript("/ig/ll"+window.location.search,"")}}function f(){d(c,b);b=[]}return{init:function(){},load:function(g,h,j){if(_gel(g))j(h);else{b.push({id:g,args:h,callback:j});if(!a)if(c)f();else{_sendx("/ig/ui?action=lazy&id="+g,ig_b,ig_c,ig_b);e()}}},loaded:function(g,h){c=g;d=h;a=ig_c;f()},Kb:function(){a=ig_c;b=[];d=c=ig_b}}}(),_IG_LL_init=ig_O.init,_IG_LL_load=ig_O.load,_IG_LL_loaded=ig_O.loaded;function _IG_MD_Generate(a){var b={t:{},dt:[],m:{},f:{}};ig_Qa(a,b);ig_Ra(a,b);ig_Sa(a,b);if(a.ct!=ig_b&&b.t)b.ct=b.t[a.ct];ig_Ta(a,b);return b}function ig_Qa(a,b){if(a.t)for(var c=0;c<a.t.length;++c){var d=a.t[c];b.t[d.i]=d;b.t[d.i].m={}}}function ig_Ra(a,b){if(a.f)for(var c=0;c<a.f.length;++c){var d=a.f[c];b.f[d.n]=d}}function ig_Sa(a,b){if(a.m)for(var c=0;c<a.m.length;++c){var d=a.m[c];if(!d.fa)d.fa={};b.m[d.i]=d;var e=b.t[d.t];if(e)e.m[d.i]=d}}
function ig_Ta(a,b){if(a.dt)for(var c=0;c<a.dt.length;++c)b.dt[c]=b.t[a.dt[c]]};var _IG_time=function(){function a(){return(new Date).getTime()}var b=window._IG_time_epoch||a(),c={},d={},e={set_epoch:function(f){b=f},start:function(f){c[f]=a();e.start_callback(f)},since:function(f){var g=c[f]||b;return a()-g},stop:function(f){d[f]=e.since(f);e.stop_callback(f)},get:function(f){return d[f]},print:function(f){document.write("<div style='color:#999999;font-size:75%'>"+f+" : "+e.get(f)+"ms</div>")},stop_and_print:function(f){e.stop(f);e.print(f)},start_callback:function(){},stop_callback:function(){}};
return e}();function _IG_Prefs_PrefsData(){}_IG_Prefs_PrefsData.prototype.value=ig_b;
function _IG_Prefs(a){var b=a;if(typeof remote_modules!=="object"){var c=_args().mid;b=c?c:0;_IG_Prefs._parseURL(b);_IG_Prefs.V[b]=ig_c}else{if(!b)throw new Error("Module ID is required as first argument to _IG_Prefs() for inlined modules");_IG_Prefs.V[b]=ig_a}_IG_Prefs.d[_IG_Prefs.w+b]||(_IG_Prefs.d[_IG_Prefs.w+b]={});this.d=_IG_Prefs.d[_IG_Prefs.w+b];this.wa=b;this.Jb=/(.*)(\<ph.*?\>\s*(\<ex\>(.*?)\<\/ex\>)?\s*%1\s*\<\/ph\>)(.*)/}
_IG_Prefs.prototype.T=function(a,b){if(b==undefined)b=ig_b;var c=this.d[a];if(c==undefined)return b;var d=c.value;return d!=undefined?d:b};_IG_Prefs.prototype.S=function(a,b){return this.T(_IG_Prefs.h+a,b)};_IG_Prefs.prototype.H=function(a){var b="",c=this.S(a,b);return c!=ig_b?c+"":b};_IG_Prefs.prototype.ma=function(a){var b=0,c=parseInt(this.S(a,b),10);return isNaN(c)?b:c};_IG_Prefs.prototype.ka=function(a){var b=this.H(a);return b==="true"||!!parseInt(b,10)};
_IG_Prefs.prototype.ja=function(a){return _IG_Prefs._strToArray(this.S(a,""))};_IG_Prefs.prototype.Da=function(a,b){this.set(a,_IG_Prefs._arrayToStr(b))};_IG_Prefs.prototype.la=function(){return this.H(".country")};_IG_Prefs.prototype.na=function(){return this.H(".lang")};_IG_Prefs.prototype.oa=function(a){return this.T(_IG_Prefs.Ja+a,"")+""};
_IG_Prefs.prototype.set=function(){var a=Math.floor(arguments.length/2);if(!(a==0)){for(var b=[],c=[],d=0;d<a;++d){var e=arguments[d*2],f=_IG_Prefs.h+e,g=arguments[d*2+1]+"";if(this.db(f,g)){b.push(f,g);c.push(e,g)}}b.length==0||(_IG_Prefs.V[this.wa]?_IG_Prefs._setP(this.wa,c):_IFPC_SetPref(c))}};_IG_Prefs.prototype.pa=function(){var a=["__module_id__="+this.wa];for(var b in this.d)a.push(encodeURIComponent(b)+"="+encodeURIComponent(this.d[b].value));return a.join("&")};
_IG_Prefs.prototype.dump=function(){document.write("<pre>");for(var a in this.d)document.writeln(a+" = "+this.T(a,ig_b));document.write("</pre>")};_IG_Prefs.prototype.db=function(a,b){var c=this.d[a];if(c&&c.value===b)return ig_c;if(c)c.value=b;else{c=new _IG_Prefs_PrefsData;c.value=b;this.d[a]=c}return ig_a};_IG_Prefs.V={};_IG_Prefs.d={};_IG_Prefs.w="m_";_IG_Prefs.h="up_";_IG_Prefs.fb="up_";_IG_Prefs.Ja="msg_";_IG_Prefs.$={};_IG_Prefs.$[_IG_Prefs.fb]="value";
_IG_Prefs.Ib=function(a,b){if(a.indexOf)return a.indexOf(b);else{for(var c=0;c<a.length;++c)if(a[c]===b)return c;return-1}};
_IG_Prefs._parseURL=function(a){_IG_Prefs.V[a]=ig_c;for(var b={},c=ig_d(),d=0;d<c.length;++d){var e=c[d].indexOf("=");if(e>=0){var f=c[d].substring(0,e);f=f.replace(/\+/g," ");var g=c[d].substring(e+1);g=g.replace(/\+/g," ");g=_unesc(g);var h=ig_c;for(var j in _IG_Prefs.$)if(f.indexOf(j)===0){h=ig_a;f=f.substring(j.length);f=_IG_Prefs.h+f;b[f]=b[f]?b[f]:new _IG_Prefs_PrefsData;if(j===_IG_Prefs.Hb||j===_IG_Prefs.Gb)g=g=="true";b[f][_IG_Prefs.$[j]]=g;break}if(!h)if(f.indexOf(_IG_Prefs.Ja)===0)_IG_Prefs._add(a,
f,g);else if(f===".lang"||f===".country")_IG_Prefs._add(a,_IG_Prefs.h+f,g)}}if(window.IDIModule){b=window.IDIModule.getPrefs();for(d in b)_IG_Prefs._add(a,d,b[d])}else for(f in b)_IG_Prefs._add(a,f,b[f].value)};_IG_Prefs._add=function(a,b,c){var d=_IG_Prefs.w+a;if(typeof _IG_Prefs.d[d]!=="object")_IG_Prefs.d[d]={};if(typeof _IG_Prefs.d[d][b]!=="object"){_IG_Prefs.d[d][b]=new _IG_Prefs_PrefsData;var e=_IG_Prefs.d[d][b];e.value=c}};
_IG_Prefs.Bb=function(a,b,c){var d=_IG_Prefs.w+a;if(typeof _IG_Prefs.d[d]!=="object")_IG_Prefs._add(a,b,c);else if(typeof _IG_Prefs.d[d][b]!=="object")_IG_Prefs.d[d][b]=new _IG_Prefs_PrefsData;var e=_IG_Prefs.d[d][b];e.value=c};_IG_Prefs._addAll=function(a,b){for(var c=0;c<b.length;++c)_IG_Prefs._add(a,b[c][0],b[c][1])};_IG_Prefs._arrayToStr=function(a){var b=a.length&&a.join;if(b){for(var c=[],d=0;d<a.length;++d)c.push(a[d].replace(/\|/g,"%7C"));return c.join("|")}else return new String(a)};
_IG_Prefs._strToArray=function(a){for(var b=a.length>0?a.split("|"):[],c=0;c<b.length;++c)b[c]=b[c].replace(/%7C/g,"|");return b};
_IG_Prefs._updatePrefsInUrl=function(a,b){var c=_IG_Prefs.w+a,d=_IG_Prefs.d[c];if(d==ig_b)return b;for(var e=b.split("&"),f=0;f<e.length;++f)e[f].indexOf(_IG_Prefs.h)===0&&e.splice(f--,1);for(var g in d)g.indexOf(_IG_Prefs.h)!==0||g.indexOf(_IG_Prefs.h+".lang")===0||g.indexOf(_IG_Prefs.h+".country")===0||g.indexOf(_IG_Prefs.h+"synd")===0||e.push(_esc(g)+"="+_esc(d[g].value));return e.join("&")};
_IG_Prefs._setPrefs=function(a,b){for(var c=Math.floor(b.length/2),d=0;d<c;++d){var e=_IG_Prefs.h+b[d*2],f=b[d*2+1];_IG_Prefs.Bb(a,e,f)}};_IG_Prefs._setP=function(a,b){if(!(_args().synd==="open")){for(var c=Math.floor(b.length/2),d=[],e=0;e<c;++e){var f=_IG_Prefs.h+b[e*2],g=b[e*2+1];d.push(_IG_Prefs.w+a+"_"+f+"="+_esc(g))}d.length===0||_xsetp(d.join("&"))}};
_exportClass("google.gadgets","Prefs",_IG_Prefs,["getString",_IG_Prefs.prototype.H,"getInt",_IG_Prefs.prototype.ma,"getBool",_IG_Prefs.prototype.ka,"getArray",_IG_Prefs.prototype.ja,"setArray",_IG_Prefs.prototype.Da,"getLang",_IG_Prefs.prototype.na,"getCountry",_IG_Prefs.prototype.la,"getMsg",_IG_Prefs.prototype.oa,"getPreloadedString",_IG_Prefs.prototype.pa,"set",_IG_Prefs.prototype.set,"dump",_IG_Prefs.prototype.dump]);function _IG_FR_toggle(a,b,c,d){c=c||"";d=d||"";var e=_gel("ft_"+a+"_"+b),f=_gel("fb_"+a+"_"+b),g=_gel("ftl_"+a+"_"+b);if(f.style.display=="block")ig_P(e,f,g,c);else{var h=eval("FEED"+a);if(!h.has_entries&&!h.is_fetching){h.is_fetching=ig_a;_IG_FetchFeedAsJSON(h.url,_IG_Callback(ig_Ua,a,b,c,d),h.num_items+15,ig_a)}else{for(var j=0;j<eval("FEED"+a).num_items;j++){var i=_gel("ftl_"+a+"_"+j);i&&ig_P(_gel("ft_"+a+"_"+j),_gel("fb_"+a+"_"+j),i,c)}ig_Va(a,b,e,f,g,d);if(f.style.maxHeight&&parseInt(f.style.maxHeight,
10)<ig_Wa(g.offsetWidth,f))f.style.height=f.style.maxHeight}}}function ig_Ua(a,b,c,d,e){var f=eval("FEED"+b);f.is_fetching=ig_c;if(a&&a.Entry){for(var g=0;g<a.Entry.length;g++)if(a.Entry[g].ID!="no_id"){var h=_gel("fb_"+b+"_"+a.Entry[g].ID);if(h)h.innerHTML=a.Entry[g].Summary}eval("FEED"+b).has_entries=ig_a;_IG_FR_toggle(b,c,d,e)}}function ig_Q(a){return a.className.match("reverse_directionality$")=="reverse_directionality"}
function ig_P(a,b,c,d){a.className=ig_Q(a)?"fmaxbox_reverse_directionality":"fmaxbox";a.title=d;if(_old_html||_use_old_feed_styles)a.className="fbox fmaxbox";b.style.display="none";b.style.maxHeight="";c.className=ig_Q(a)?"uftl_reverse_directionality":"uftl"}
function ig_Va(a,b,c,d,e,f){c.className=ig_Q(c)?"fminbox_reverse_directionality":"fminbox";c.title=f;if(_old_html||_use_old_feed_styles)c.className="fbox fminbox";d.style.display="block";d.style.maxHeight=d.offsetWidth*1.5+"px";e.className=ig_Q(c)?"sftl_reverse_directionality":"sftl";window._IG_FRUC_setFeedAsRead&&window._IG_FRUC_setFeedAsRead(a,b)}
function ig_Wa(a,b){var c=document.createElement("div");c.style.left=-screen.width;c.style.top=-screen.height;c.style.width=a;c.innerHTML=b.innerHTML;document.body.appendChild(c);var d=c.clientHeight;document.body.removeChild(c);return d}function _IG_RegisterContainerScrollHandler(a){if(navigator.userAgent.indexOf("Firefox")>=0)window.addEventListener("scroll",a,ig_c);else window.onscroll=a}function _IG_GetContainerVisibleHeight(){return document.documentElement.clientHeight}
function _IG_GetContainerTotalHeight(){return document.body.scrollHeight}function _IG_GetContainerScrollTop(){return document.documentElement.scrollTop}function ig_R(a){var b=_gel("hl"),c=b?b.value:"en";return"/reader/ig/feed/"+_esc(eval("FEED"+a).url)+"?hl="+c}function ig_S(a,b){if(window._max_strategies){var c=ig_R(a)+(b?"&i="+b:"");window._max_strategies[a]._updateIframeSrc(c)}}function _IG_FR_maxModule(a,b,c){ig_S(a,b);window._IG_maximize_view(a,"feed",c)}
function _IG_FR_init(a){window._max_strategies&&_IG_callPostLoad(function(){window._max_strategies[a]=new window._IG_inlinedTransitionStrategy(a,ig_R(a),ig_b,_IG_isIE())});_IG_AddModuleEventHandler(a,"unmaximize",function(){ig_S(a)})}var _IG_FR_listOfFeeds=[];function ig_Xa(a,b,c,d){if(!a||a==""||a.length<=27||a.charAt(27)!="{")c(d?ig_b:"");else{var e=eval("("+a.substring(27)+")");if(b in e){var f=e[b].body;c(d?ig_T(f):f)}}}function ig_Ya(a){var b;if(window.ActiveXObject){b=new ActiveXObject("Microsoft.XMLDOM");b.async=ig_c;b.validateOnParse=ig_c;b.resolveExternals=ig_c;b.loadXML(a)}else{var c=new DOMParser;b=c.parseFromString(a,"text/xml")}return b}
function ig_T(a){var b=ig_Ya(a),c=b.documentElement;if(c&&c.nodeName=="parsererror"||navigator.userAgent.indexOf("Safari")>=0&&_gelstn("parsererror",b)[0])return a;return b}var ig_Za=(new Date).getTime();
function ig_U(a){if(!a.post_data&&!a.headers&&window._pl_data&&_pl_data[a.url]&&!(!isNaN(a.refreshInterval)&&a.refreshInterval>=0&&(new Date).getTime()>ig_Za+a.refreshInterval*1000))if(a.asXml){var b=ig_T(_pl_data[a.url]);a.callback(b)}else a.callback(_pl_data[a.url]);else{var c="/ig/jsonp?";if(_et!="")c+="et="+_et+"&";if(!isNaN(a.refreshInterval)&&a.refreshInterval>=0)c=_appendMaxAgeParameter(c,a.refreshInterval);if(a.encoding)c+="enc="+_esc(a.encoding)+"&";if(a.headers){for(var d=[],e=0;e<a.headers.length;e++)d.push(_esc(a.headers[e][0]+
":"+a.headers[e][1]));c+="hdrs="+_esc(d.join(","))+"&"}c+="url="+_esc(a.url);_sendx(c,function(f){ig_Xa(f,a.url,a.callback,a.asXml)},ig_c,a.post_data)}}function ig_V(a){var b={};for(var c in a)b[c]=a[c];return b}function _IG_FetchContent(a,b,c){var d;d=c!=ig_b&&typeof c=="object"?ig_V(c):{};d.url=a;d.callback=b;d.asXml=ig_c;ig_U(d)}function _IG_FetchXmlContent(a,b,c){var d;d=c!=ig_b&&typeof c=="object"?ig_V(c):{};d.url=a;d.callback=b;d.asXml=ig_a;ig_U(d)}
function ig__a(a,b,c){_IG_FetchContent(a,function(d){if(d){var e=ig_T(d);if(typeof e=="object"&&e.firstChild){var f=e.firstChild;f.nodeType==7&&f.nodeName=="xml"&&e.removeChild(f);b(e);return}}b(ig_b)},c)}function ig_0a(a,b){var c="/ig/feedjson";_sendx(c,function(d){var e={};try{e=eval("("+d.slice(27)+")")}catch(f){e={}}for(var g in b){var h=e[g]?e[g]:ig_b;b[g](h)}b=ig_b},ig_c,a)}var ig_1a=ig_c,ig_2a=0,ig_W="",ig_X={};
function _IG_FetchFeedAsJSON(a,b,c,d,e){if(typeof e!="object")e={};var f="fr_"+ig_2a++,g="url="+_esc(a);if(!isNaN(e.refreshInterval)&&e.refreshInterval>=0)g=_appendMaxAgeParameter(g,e.refreshInterval);if(c)g+="&val="+_esc(c);if(d)g+="&sum=1";var h=f+"="+_esc(g);if(ig_1a){var j={};j[f]=b;ig_0a(h,j)}else{if(ig_W!="")ig_W+="&";ig_W+=h;ig_X[f]=b}}function ig_3a(){ig_1a=ig_a;ig_W!=""&&ig_0a(ig_W,ig_X);ig_W="";ig_X=ig_b}_IG_AddEventHandler("domload",ig_3a);
_exportSymbols("google.gadgets.Fetchers",["getContent",_IG_FetchContent,"getXMLContent",ig__a,"getFeedAsJSON",_IG_FetchFeedAsJSON]);var ig_Y={va:"javascript:void(0);",pb:{u:"",ti:"",mt:""},gmc:function(a,b){return[IG_MSGS.GMC,ig_j(IG_URLS.gmc,["moduleurl="+_esc(b.u),"mid="+a]),ig_b]},gmp:function(a){return[IG_MSGS.GMP,ig_j(IG_URLS.gmp,["mid="+a]),ig_b]},gmi:function(a,b){return[IG_MSGS.GMI,ig_j(IG_URLS.gmi,["moduleurl="+_esc(b.u),"mid="+a,"moduletitle="+_esc(_hesc(b.ti))]),ig_b]},ed:function(a,b){var c=b.eh?window[b.eh]:ig_b;return[IG_MSGS.ED,ig_Y.va,ig_L(_edit,a,c)]},Ta:function(a,b,c){var d=ig_L(_confirmDel,a,b.mt,"n_"+b.mt+
"="+_esc("url="+_esc(b.u)),c.replace("MODULE_TITLE",b.ti));return[IG_MSGS.DEL,ig_Y.va,d]},del:function(a,b){return ig_Y.Ta(a,b,IG_MSGS.DEL_CONFIRM)},del2:function(a,b){return ig_Y.Ta(a,b,IG_MSGS.DEL_CONFIRM2)},ming:function(a,b){return[IG_MSGS.MING,ig_Y.va,ig_L(_zm,a,b.mt)]},maxg:function(a,b){var c=ig_Y.ming(a,b);c[0]=IG_MSGS.MAXG;return c},shg:function(a,b){var c=ig_L(_share_this_gadget,IG_MSGS.SHG,ig_j(IG_URLS.sgu,["moduleurl="+_esc(b.u),"mid="+a,"source=share_gadget"]),a);return[_hesc(IG_MSGS.SHG),
"#",function(){c();return ig_c}]},Cb:/^http:\/\//,bb:function(a){return _esc(a.replace(ig_Y.Cb,""))},rg:function(a,b){return ig_Y.rgv1(a,b).concat("dd_separator")},rgv1:function(a,b){return[IG_MSGS.RG,ig_j(IG_URLS.dir,["recommend="+ig_Y.bb(b.u)]),ig_b]},ag:function(a,b){return[IG_MSGS.AG,ig_j(IG_URLS.dir,["url="+ig_Y.bb(b.u)]),ig_b]}};_exportSymbols("",["_IG_DDI",ig_Y]);var ig_Z;
ig_Z||(ig_Z=function(){function a(i){return i<10?"0"+i:i}Date.prototype.r=function(){return this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z"};String.prototype.r=Number.prototype.r=Boolean.prototype.r=function(){return this.valueOf()};var b=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,c=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,d,
e,f={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},g;function h(i){c.lastIndex=0;return c.test(i)?'"'+i.replace(c,function(k){var l=f[k];if(typeof l==="string")return l;return"\\u"+("0000"+(+k.charCodeAt(0)).toString(16)).slice(-4)})+'"':'"'+i+'"'}function j(i,k){var l,o,p,q,r=d,m,n=k[i];if(n&&typeof n==="object"&&typeof n.r==="function")n=n.r(i);if(typeof g==="function")n=g.call(k,i,n);switch(typeof n){case "string":return h(n);case "number":return isFinite(n)?
String(n):"null";case "boolean":case "null":return String(n);case "object":if(!n)return"null";d+=e;m=[];if(typeof n.length==="number"&&!n.propertyIsEnumerable("length")){q=n.length;for(l=0;l<q;l+=1)m[l]=j(l,n)||"null";p=m.length===0?"[]":d?"[\n"+d+m.join(",\n"+d)+"\n"+r+"]":"["+m.join(",")+"]";d=r;return p}if(g&&typeof g==="object"){q=g.length;for(l=0;l<q;l+=1){o=g[l];if(typeof o==="string")if(p=j(o,n))m.push(h(o)+(d?": ":":")+p)}}else for(o in n)if(Object.hasOwnProperty.call(n,o))if(p=j(o,n))m.push(h(o)+
(d?": ":":")+p);p=m.length===0?"{}":d?"{\n"+d+m.join(",\n"+d)+"\n"+r+"}":"{"+m.join(",")+"}";d=r;return p}}return{stringify:function(i,k,l){var o=k,p=l,q;e=d="";if(typeof p==="number")for(q=0;q<p;q+=1)e+=" ";else if(typeof p==="string")e=p;if((g=o)&&typeof o!=="function"&&(typeof o!=="object"||typeof o.length!=="number"))throw new Error("JSON.stringify");return j("",{"":i})},parse:function(i,k){var l=k,o;function p(q,r){var m,n,s=q[r];if(s&&typeof s==="object")for(m in s)if(Object.hasOwnProperty.call(s,
m)){n=p(s,m);if(n!==undefined)s[m]=n;else delete s[m]}return l.call(q,r,s)}b.lastIndex=0;if(b.test(i))i=i.replace(b,function(q){return"\\u"+("0000"+(+q.charCodeAt(0)).toString(16)).slice(-4)});if(/^[\],:{}\s]*$/.test(i.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){o=eval("("+i+")");return typeof l==="function"?p({"":o},""):o}throw new Error("JSON.parse");}}}());
ig_Z.parse=function(){var a=ig_Z.parse;return function(b,c){try{return a(b,c)}catch(d){return ig_c}}}();function ig_4a(a){var b=document.createElement("DIV");b.innerHTML="<iframe onload='this.pool_locked=false'></iframe>";var c=b.getElementsByTagName("IFRAME")[0];c.style.visibility="hidden";c.style.width=c.style.height="0px";c.style.border="0px";c.style.position="absolute";c.pool_locked=a;this.g[this.g.length]=c;b.removeChild(c);return c}
function ig_5a(a){if(a.match(/^http[s]?:\/\//)){var b=this;window.setTimeout(function(){for(var c=ig_b,d=b.g.length-1;d>=0;d--){var e=b.g[d];if(e&&!e.pool_locked){e.parentNode.removeChild(e);if(window.ActiveXObject){b.g[d]=ig_b;b.g.splice(d,1)}else{e.pool_locked=ig_a;c=e;break}}}c=c?c:b.mb(ig_a);c.src=a;document.body.appendChild(c)},0)}}function ig_6a(){for(var a=0;a<this.g.length;a++){this.g[a].onload=ig_b;this.g[a]=ig_b}this.g.length=0;this.g=[]}
function ig_7a(){for(var a=0;a<this.g.length;a++){var b=this.g[a];b&&b.parentNode.removeChild(b)}}function ig_8a(){this.g=[];this.mb=ig_4a;this.iframe=ig_5a;this.clear=ig_6a;this.dispose=ig_7a}function ig_9a(a,b){_IFPC.N[a]=b}function ig_$a(a){delete _IFPC.N[a]}
function ig_ab(a,b,c,d,e,f,g,h){if(!_IFPC.ga){var j=4095-d.length;j=parseInt(j/3,10);if(typeof g=="undefined")g=ig_a;if(h){var i={s:b,a:c,f:"..",t:window._isk[a.split("_")[2]]},k=[a,"..",_IFPC.callCounter,1,1,encodeURIComponent(ig_Z.stringify(i))].join("&");_IFPC.U.iframe(d+"#"+k)}else{c=c.slice(0);c.unshift(_IFPC.zb(e));c.unshift(f);c.unshift(b);c.unshift(a);var l=_IFPC.Ua(c),o=parseInt(l.length/j,10);if(l.length%j>0)o+=1;for(var p=0;p<o;p++){var q=l.substr(p*j,j),r=[a,_IFPC.Qa,o,p,q,g];_IFPC.U.iframe(d+
"#"+_IFPC.Ua(r))}}_IFPC.Qa++}}function ig_bb(){_IFPC.N={};_IFPC.C={};_IFPC.U.clear()}function ig_cb(){if(!_IFPC.ga){_IFPC.ga=ig_a;_IFPC.U.dispose();_IFPC.clear()}}
function ig_db(a){var b=_IFPC.ea(a)[0],c=ig_b;try{c=window.parent.frames[b]}catch(d){}try{if(!c&&window.parent.parent.frames[b]!=window.parent){window.parent.parent.frames[b].setTimeout(function(){},0);c=window.parent.parent.frames[b]}}catch(e){}if(!c)c=window.parent.parent;if(!c||c._IFPC==undefined)c=ig_b;else{var f=function(){c._IFPC.handleRequest(a)};window.ActiveXObject?f():c.setTimeout(f,0)}}
function ig_eb(a){a=_IFPC.ea(a);var b=a.shift(),c=a.shift(),d=a.shift(),e=a.shift(),f=a.shift(),g=a.shift(),h=b+"_"+c;_IFPC.A[h]||(_IFPC.A[h]=[]);_IFPC.A[h].push([e,f]);if(_IFPC.A[h].length==d){_IFPC.A[h].sort(function(r,m){return parseInt(r[0],10)-parseInt(m[0],10)});f="";for(var j=0;j<d;j++)f+=_IFPC.A[h][j][1];_IFPC.A[h]=ig_b;var i=_IFPC.ea(f);b=i.shift();var k=i.shift(),l=i.shift(),o=i.shift(),p=_IFPC.ub(k);if(p){var q=p.apply(ig_b,i);if(_IFPC.xb(o)){q.unshift(o);_IFPC.call(b,_IFPC.Ga,q,l,ig_b,
"")}}else if(g)throw new Error("Service "+k+" not registered.");}}function ig_fb(a){return _IFPC.N.hasOwnProperty(a)?_IFPC.N[a]:ig_b}function ig_gb(a){var b="";if(a&&typeof a=="function"){b=_IFPC.tb();_IFPC.C[b]=a}return b}function ig_hb(a){if(_IFPC.C.hasOwnProperty(a))_IFPC.C[a]=ig_b}function ig_ib(a){if(a&&_IFPC.C.hasOwnProperty(a))return _IFPC.C[a];return ig_b}function ig_jb(){return _IFPC.Fa+_IFPC.kb++}function ig_kb(a){return(a+"").indexOf(_IFPC.Fa)==0}
function ig_lb(a){for(var b=a.split("&"),c=0;c<b.length;c++){var d=decodeURIComponent(b[c]);try{d=ig_Z.parse(d)}catch(e){}b[c]=d}return b}function ig_mb(a){for(var b=[],c=0;c<a.length;c++){var d=ig_Z.stringify(a[c]);b.push(encodeURIComponent(d))}return b.join("&")}function ig_nb(a){var b=_IFPC.rb(a);if(b){for(var c=[],d=1;d<arguments.length;d++)c[c.length]=arguments[d];b.apply(ig_b,c);_IFPC.Fb(a)}else throw new Error("Invalid callbackId");}var _IFPC;
function ig_ob(a){var b=window._argsUrl&&window._argsUrl(a);if(b&&b.exp_rpc_js==1)window.FLAG_use_rpc_js=ig_a;if(window.FLAG_use_rpc_js)_IFPC={registerService:function(c,d){window.gadgets.rpc.register(c,function(){var e=this.a.slice(0);e.unshift(this.f);d.apply(ig_b,e)})},unregisterService:function(c){window.gadgets.rpc.unregister(c)},call:function(c,d,e,f,g,h,j,i){var k=window.gadgets.rpc;if(f==k.getRelayUrl(".."))c="..";e||(e=[]);i||(e=e.slice(1));e.unshift(g);e.unshift(d);e.unshift(c);k.call.apply(k,
e)}};else{_IFPC={registerService:ig_9a,unregisterService:ig_$a,call:ig_ab,clear:ig_bb,dispose:ig_cb,relayRequest:ig_db,processRequest:ig_db,handleRequest:ig_eb,Fa:"cbid",Ga:"ifpc_callback",U:new ig_8a,A:{},N:{},C:{},kb:0,Qa:0,ga:ig_c,ub:ig_fb,zb:ig_gb,Fb:ig_hb,rb:ig_ib,tb:ig_jb,xb:ig_kb,ea:ig_lb,Ua:ig_mb,lb:ig_nb};_IFPC.registerService(_IFPC.Ga,_IFPC.lb)}}ig_ob(document.location.href);function ig_pb(a,b,c){var d=_gel("m_"+b+"_title");if(d)d.innerHTML=_hesc(a);if(d=_gel("left_nav_m_"+b+"_title"))if(d=d.firstChild){d.title=a;d.innerHTML=_hesc(a);var e=window.FLAG_use_js_leftnav_inactive_tab_format==ig_a&&c;if(window.FLAG_use_js_leftnav_title_format==ig_a&&!e)d.offsetWidth==0?_IG_RegisterOnloadHandler(function(){ig__(d)}):ig__(d)}}
function ig__(a){var b=a.title;if(!(a.offsetWidth<=121)){var c=0,d=b.length,e,f,g=b.match(/\(\d+\)$/);if(g=g?g[0]:""){g=" "+g;d=b.length-g.length;var h=5*g.length;if(h>60)g=""}for(;f=d-c>>1;){e=c+f;a.innerHTML=ig_qb(b,e,g);if(a.offsetWidth>121)d=e;else c=e}a.innerHTML=ig_qb(b,c,g)}}function ig_qb(a,b,c){var d=[a.substring(0,b),"..."];c&&d.push(c);return _hesc(d.join(""))}function ig_rb(a){return typeof a=="undefined"||!a||a=="undefined"}function ig_sb(a,b){ig_rb(a)||ig_pb(b,_ig_gmid_(a))}
_IFPC.registerService("set_title",ig_sb);function _IG_SetTitle(a,b,c){if(ig_rb(b))throw new Error("Inline modules must specify their __MODULE_ID__ when using _IG_SetTitle");else ig_pb(a,b,c)}function _IG_FormatLeftNavTitles(){_IG_RegisterOnloadHandler(function(){var a=_gel("full_nav"),b=_gelsbyregex("div",/^left_nav_m_\d+_title$/,a);if(b)for(var c=0;c<b.length;++c)if(window.FLAG_use_js_leftnav_title_format==ig_a){var d=b[c];(d=d.firstChild)&&ig__(d)}})};var ig_0,ig_1,ig_2={};function _IG_AddDropDownEventHandler(a,b){ig_2[a]=b}function _IG_DD_init(){var a=document.createElement("iframe");a.id="IG_DD_iframe_cover";a.className="dd_iframe_cover";a.style.display="none";document.body.insertBefore(a,document.body.firstChild);var b=document.createElement("div");b.id="IG_DD_div";b.className="dd_layer_hidden";b.onclick=_IG_DD_hide;document.body.insertBefore(b,document.body.firstChild)}
function _IG_DD_create(a,b){var c=document.createElement("div");c.setAttribute("id","DD_"+a);c.className="dd dd_border";c.style.display="none";c.onkeydown=_IG_DD_keys;for(var d=0,e;e=b[d];d++){var f=e;if(typeof e=="function"){var g=window._IG_MD?_IG_MD.m[a]:_DD["m_"+a];f=e(a,g||ig_Y.pb)}f[3]&&c.appendChild(ig_tb(f[3]));c.appendChild(_IG_DD_add(f[0],f[1],f[2],d))}_gel("IG_DD_div").appendChild(c)}
function _IG_DD_add(a,b,c,d){b=b||"javascript:void(0)";var e=document.createElement("div"),f="";if(typeof c=="string"&&c!="")f=' onclick="'+c+'"';e.innerHTML='<a href="'+b+'"'+f+">"+a+"</a>";var g=e.firstChild;if(typeof c=="string"&&c!="")c=g.onclick;if(c)g.onclick=function(h){c(h);_IG_DD_hide();return ig_c};g.className=d==0?"dd_item dd_item_first":"dd_item";g.onblur=function(){ig_1=ig_c;return ig_a};g.onmouseover=function(){return _IG_DD_select(this)};return g}
function ig_tb(a){var b=document.createElement("div");b.className=a;b.innerHTML='<div class="topline"></div><div class="bottomline"></div>';return b}
function _IG_DD_open(a,b){var c=_gel("DD_"+b);if(c.style.display=="none"){ig_0=b;var d=_gel("IG_DD_div");d.className="dd_layer";_IG_AddEventHandler("resize",_IG_DD_position);_IG_DD_position();ig_1=ig_c;if(c.hasChildNodes()){var e=c.firstChild;if(e.tagName!="A")e=e.nextSibling;_IG_DD_select(e)}var f=_gel("DD_tg_"+b);f.className+=" ddbox_sel";var g=ig_2[ig_0];g&&g(ig_a)}}
function _IG_DD_position(){var a=_gel("DD_"+ig_0),b=_gel("DD_tg_"+ig_0),c=_gel("IG_DD_div");a.style.display="block";var d=_findPos(b),e=a.offsetWidth,f=d[0]+b.offsetWidth-e,g=document.body.clientWidth+document.body.scrollLeft;if(f<5)f=5;else if(f+e>g-5)f=g-5-e;a.style.left=f+"px";a.style.top=d[1]+b.offsetHeight+"px";var h=_gel("IG_DD_iframe_cover");h.style.left=a.style.left;h.style.top=a.style.top;h.style.width=a.offsetWidth+"px";h.style.height=a.offsetHeight+"px";h.style.display="block";c.style.height=
ig_J()+"px";c.style.width=document.body.clientWidth+"px"}
function _IG_DD_hide(){var a=_gel("IG_DD_div");if(a.className=="dd_layer"){_IG_RemoveEventHandler("resize",_IG_DD_position);if(ig_0){var b=_gel("DD_"+ig_0);b.style.display="none";_gel("IG_DD_iframe_cover").style.display="none";var c=_gel("DD_tg_"+ig_0);c.className=c.className.replace(/ ddbox_sel/,"");var d=ig_2[ig_0];d&&d(ig_c);if(ig_1){var e=_gel("DD_tg_"+ig_0);e&&e.focus()}ig_1=ig_c;ig_0=ig_b}a.className="dd_layer_hidden"}_IG_DD_select(ig_b)}
function _IG_DD_gcn(a,b,c){for(var d=new RegExp("(^| )"+c+"( |$)"),e=_gelstn(b,a),f=[],g=0,h;h=e[g];g++)d.test(h.className)&&f.push(h);return f}
function _IG_DD_select(a){var b=_IG_DD_gcn(_gel("IG_DD_div"),"a","dd_sel");if(b!=ig_b)for(var c=0,d;d=b[c];c++)d.className=d.className.replace(/ dd_sel/g,"");if(a){try{a.focus()}catch(e){if(!(e.message=="Can't move focus to the control because it is invisible, not enabled, or of a type that does not accept the focus."))throw e;}a.className=a.className+" dd_sel"}}
function _IG_DD_keys(a){function b(g,h){var j=g;do{j=h?j.nextSibling:j.previousSibling;if(!j){var i=g.parentNode;j=h?i.firstChild:i.lastChild}}while(j!=g&&j.tagName!="A");return j}var c=ig_a,d=_IG_DD_gcn(_gel("IG_DD_div"),"a","dd_sel");if(d==ig_b||d.length!=1)return ig_a;var e=d[0];if(!a)a=window.event;var f=a.keyCode||a.charCode||a.which;switch(f){case 13:ig_1=ig_a;break;case 38:_IG_DD_select(b(e,ig_c));c=ig_c;break;case 40:_IG_DD_select(b(e,ig_a));c=ig_c;break;case 27:case 9:ig_1=ig_a;c=ig_0==ig_b&&
f==9;_IG_DD_hide();break}return c};var ig_3={obj:ig_b,init:function(a,b){a.onmousedown=ig_3.start;a.obj=b;if(isNaN(parseInt(b.style.left,10)))b.style.left="0px";if(isNaN(parseInt(b.style.top,10)))b.style.top="0px";b.onDragStart=new Function;b.onDragEnd=new Function;b.onDrag=new Function},uninit:function(a,b){window.clearInterval(b.$a);a.onmousedown=ig_b;a.obj=ig_b;b.onDragStart=ig_b;b.onDragEnd=ig_b;b.onDrag=ig_b},start:function(a){var b=ig_3.obj=this.obj;a=ig_3.fixE(a);if(a.which!=1)return ig_a;b.onDragStart(a);var c=a.clientY;ig_.Wa||
(c+=document.body.scrollTop);b.lastMouseX=a.clientX;b.lastMouseY=c;b.offsetMouseX=parseInt(b.style.left,10)-a.clientX;b.offsetMouseY=parseInt(b.style.top,10)-c;b.$a=window.setInterval(ig_ub(b,document.body.scrollHeight>document.documentElement.clientHeight?document.body.scrollHeight:document.documentElement.clientHeight),10);document.onmouseup=ig_3.end;document.onmousemove=ig_3.drag;return ig_c},drag:function(a){a=ig_3.fixE(a);if(a.which==0)return ig_3.end();var b=ig_3.obj,c=a.clientY;ig_.Wa||(c+=
document.body.scrollTop);var d=a.clientX;if(b.lastMouseX==d&&b.lastMouseY==c)return ig_c;var e=d+b.offsetMouseX,f=c+b.offsetMouseY;b.style.left=e+"px";b.style.top=f+"px";b.lastMouseX=d;b.lastMouseY=c;b.onDrag(e,f);return ig_c},end:function(a){a=ig_3.fixE(a);document.onmousemove=ig_b;document.onmouseup=ig_b;window.clearInterval(ig_3.obj.$a);var b=ig_3.obj.onDragEnd();ig_3.obj=ig_b;return b},fixE:function(a){if(typeof a=="undefined")a=window.event;if(typeof a.layerX=="undefined")a.layerX=a.offsetX;
if(typeof a.layerY=="undefined")a.layerY=a.offsetY;if(typeof a.which=="undefined")a.which=a.button;return a}};function ig_vb(a,b,c){if(!a)return[];var d=b=="*"&&a.all?a.all:_gelstn(b,a),e=[];c=c.replace(/\-/g,"\\-");for(var f=new RegExp("(^|\\s)"+c+"(\\s|$)"),g,h=0;h<d.length;h++){g=d[h];f.test(g.className)&&e.push(g)}return e}
var _IG_initDrag=function(a,b){ig_.K=a;ig_.X=b;ig_.D=ig_vb(ig_.K,"div","yui-u");if(_old_html){ig_.Za=ig_.K.tBodies[0].rows[0];ig_.D=ig_.Za.cells}ig_.l=[];for(var c=0,d=0;d<ig_.D.length;d++){var e=ig_.D[d];if(!(e.className.indexOf("ig_dnd_fixed_col")!=-1||e.style.display=="none"))for(var f=0;f<e.childNodes.length;f++){var g=e.childNodes[f];if(g.tagName=="DIV"){ig_.l[c]=g.className!="dm"?new ig_wb(g):new ig_xb(g);c++}}}_IG_AddEventHandler("unload",ig_yb)};
function ig_yb(){if(ig_.l)for(var a=0;a<ig_.l.length;a++){ig_.l[a].P();ig_.l[a]=ig_b}ig_.l=ig_b;ig_.D=ig_b;if(_old_html)ig_.Za=ig_b;ig_.K=ig_b}var ig_={};ig_.Ea=navigator.userAgent;ig_.ta=ig_.Ea.indexOf("Gecko")!=-1;ig_.ua=ig_.Ea.indexOf("Opera")!=-1;ig_.Wa=ig_.Ea.indexOf("Safari")!=-1;ig_.La="IG_pageDivMaskId";ig_.Ka="IG_moduleDivMaskId";ig_.ob=function(){ig_.K.style.display="none"};ig_.qb=function(){ig_.K.style.display=""};ig_.B=ig_b;
ig_.G=function(){if(!ig_.B){ig_.B=document.createElement("DIV");ig_.B.className="modbox";ig_.B.backgroundColor="";ig_.B.style.border="2px dashed #aaa";ig_.B.innerHTML="&nbsp;"}return ig_.B};ig_.p=function(a,b){return function(){return a[b].apply(a,arguments)}};
ig_.Va=function(){var a=[];if(ig_.X){var b;b=_old_html?ig_.X.tBodies[0].rows[0].cells:_gelstn("LI",ig_.X);for(var c=0;c<b.length;c++){var d=b[c];(" "+d.className+" ").indexOf(" unselectedtab ")<0||d.style.display=="none"||a.push(d)}b=_gelstn("DIV",ig_.X);for(c=0;c<b.length;c++){d=b[c];(" "+d.className+" ").indexOf(" leftunselectedtab ")<0||d.style.display=="none"||a.push(d)}}return a};
ig_.jb=function(){for(var a=ig_.Va(),b=0;b<a.length;b++){var c=a[b];c.isDraggableTo=ig_a;c.pagePosLeft=ig_.k(c,ig_a);c.pagePosRight=c.pagePosLeft+c.offsetWidth;c.pagePosTop=ig_.k(c,ig_c);c.pagePosBottom=c.pagePosTop+c.offsetHeight}};ig_.ib=function(a){for(var b=0;b<ig_.l.length;b++){var c=ig_.l[b];c.b.pagePosLeft=ig_.k(c.b,ig_a);c.b.pagePosTop=ig_.k(c.b,ig_c)}for(var d=a.b.nextSibling;d;){d.pagePosTop-=a.b.offsetHeight;d=d.nextSibling}};
ig_.k=function(a,b){var c=0,d=0;if(a&&a.offsetParent&&a.offsetParent.id)if(!b){var e=_gelstn(a.tagName,a.offsetParent);if(e&&e[0])d=e[0].offsetTop}for(;a;){c+=a["offset"+(b?"Left":"Top")];a=a.offsetParent}return c-d};
ig_.Na=function(a){ig_.Ba();var b=document.createElement("DIV");b.id=ig_.La;b.innerHTML="&nbsp;";b.style.position="absolute";b.style.width="100%";b.style.height=document.body.offsetHeight+"px";b.style.left="0px";b.style.top="0px";b.style.backgroundImage="url(http://www.google.com/c.gif)";b.style.zIndex="9999";document.body.appendChild(b);if(a.vb){b=b.cloneNode(ig_a);b.id=ig_.Ka;b.style.height=a.b.offsetHeight-a.j.offsetHeight+"px";b.style.top=a.j.offsetHeight+"px";a.b.appendChild(b)}};
ig_.Ba=function(){for(var a=[ig_.Ka,ig_.La],b=0;b<a.length;b++){var c=_gel(a[b]);c&&c.parentNode.removeChild(c)}};ig_.Ab=function(){for(var a="",b=0;b<ig_.D.length;b++)for(var c=ig_.D[b],d=0;d<c.childNodes.length-1;d++){var e=c.childNodes[d];if(e.tagName=="DIV"){a+=a!=""?":":"";a+=e.id.substring(2)+"_"+c.id.substring(2)}}_xsetp("mp="+_esc(a))};function ig_xb(a){this.P=ig_zb;this.b=a;this.b.innerHTML="<br />"}function ig_zb(){this.b=ig_b}
function ig_wb(a){this._urlMouseUp=ig_Ab;this._urlMouseDown=ig_Bb;this._urlClick=ig_Cb;this._dragStart=ig_Db;this._drag=ig_Eb;this._dragEnd=ig_Fb;this.ia=ig_Gb;this.Z=ig_Hb;this.P=ig_Ib;this.o=ig_c;this.b=a;this.j=_gel(a.id+"_h");this.e=_gel(a.id+"_url");this.vb=_gelstn("IFRAME",this.b).length>0;this.b.DND_Module=this;if(this.j){this.j.style.cursor="move";ig_3.init(this.j,this.b);this.b.onDragStart=ig_.p(this,"_dragStart");this.b.onDrag=ig_.p(this,"_drag");this.b.onDragEnd=ig_.p(this,"_dragEnd");
if(this.e){this.e.style.cursor="pointer";if(ig_.ta){this.e.onmousedown=ig_.p(this,"_urlMouseDown");this.e.onclick=ig_.p(this,"_urlClick")}else this.e.onmouseup=ig_.p(this,"_urlMouseUp")}}}function ig_Ib(){if(this.j){if(this.e){this.e.onclick=ig_b;this.e=this.e.onmouseup=ig_b}ig_3.uninit(this.j,this.b);this.b.onDragStart=ig_b;this.b.onDrag=ig_b;this.j=this.b.onDragEnd=ig_b}this.b=ig_b}
function ig_Ab(a){a=ig_3.fixE(a);if(this.o||!this.e||!this.e.href||a.which!=1)return ig_a;this.Z("titleclick");if(this.e.target||a.shiftKey)window.open(this.e.href,this.e.target);else document.location=this.e.href;return ig_c}function ig_Bb(a){a=ig_3.fixE(a);a.stopPropagation();return ig_a}function ig_Cb(){if(!this.o&&this.e&&this.e.href){this.Z("titleclick");return ig_a}return ig_c}
function ig_Db(){ig_.ib(this);ig_.jb();this.origNextSibling=this.b.nextSibling;var a=ig_.G(),b=this.b.offsetHeight;b-=parseInt(a.style.borderTopWidth,10)*2;var c=this.b.offsetWidth,d=ig_.k(this.b,ig_a),e=ig_.k(this.b,ig_c);this.b.style.width=c+"px";a.style.height=b+"px";this.b.parentNode.insertBefore(a,this.b.nextSibling);this.b.style.position="absolute";this.b.style.zIndex=10000;this.b.style.left=d+"px";this.b.style.top=e+"px";ig_.Na(this);return this.o=ig_c}
function ig_Jb(){var a=0,b=0;if(typeof window.pageYOffset=="number"){a=window.pageXOffset;b=window.pageYOffset}else if(document.body&&(document.body.scrollLeft||document.body.scrollTop)){a=document.body.scrollLeft;b=document.body.scrollTop}else if(document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)){a=document.documentElement.scrollLeft;b=document.documentElement.scrollTop}return[a,b]}
function ig_Eb(a,b){if(!this.o){this.b.style.filter="alpha(opacity=50)";this.b.style.opacity=0.5;this.o=ig_a;this.Z("dragstart")}for(var c=ig_b,d=100000000,e=0;e<ig_.l.length;e++){var f=ig_.l[e],g=a;if(document.body.dir=="rtl"&&f.b.offsetWidth==1)g+=this.b.offsetWidth;var h=Math.sqrt(Math.pow(g-f.b.pagePosLeft,2)+Math.pow(b-f.b.pagePosTop,2));if(!(f==this))if(!isNaN(h))if(h<d){d=h;c=f}}this.z=ig_b;var j=ig_.Va();for(e=0;e<j.length;e++){f=j[e];if(f.isDraggableTo){var i=ig_Jb();if(this.b.lastMouseX>=
f.pagePosLeft&&this.b.lastMouseX<=f.pagePosRight&&this.b.lastMouseY+i[1]>=f.pagePosTop&&this.b.lastMouseY+i[1]<=f.pagePosBottom){this.z=f;var k=ig_.G();k.parentNode!=ig_b&&k.parentNode.removeChild(k);break}}}for(e=0;e<j.length;e++){f=j[e];if(f.id.indexOf("view")>=0||f.id.indexOf("contents")>=0)if(f==this.z){if(f.className.indexOf(" tab_hover")<0)f.className+=" tab_hover"}else f.className=f.className.replace(/ tab_hover/g,"")}k=ig_.G();if(this.z==ig_b&&c!=ig_b&&k.nextSibling!=c.b){c.b.parentNode.insertBefore(k,
c.b);if(ig_.ua){document.body.style.display="none";document.body.style.display=""}}}
function ig_Fb(){ig_.Ba();this.ia()&&ig_.Ab();if(this.z){var a=this.z.id.match(/.*(\d+).*/)[1],b=this.b.id.match(/m_(\d+)/)[1];_xsetp("mt="+b+":"+a);this.b.style.display="none";this.z.className=this.z.className.replace(/ tab_hover/g,"");var c=_gel("left_nav_m_"+b+"_title"),d=_gel("gadget_set"+a);if(c&&d){c.parentNode.removeChild(c);d.appendChild(c);_gelstn("a",c)[0].onclick=function(){_select_gadget_and_log(a,b)}}}_hideNewUserTip();this.o&&this.Z("dragend");return ig_a}
function _hideNewUserTip(){var a=_gel("new_user_tip");if(a)a.style.display="none"}function ig_Gb(){var a=ig_c;this.b.style.position="";this.b.style.width="";this.b.style.zIndex="";this.b.style.filter="";this.b.style.opacity="";window.scrollBy(0,0);var b=ig_.G();if(b.parentNode!=ig_b){if(b.nextSibling!=this.origNextSibling){b.parentNode.insertBefore(this.b,b.nextSibling);a=ig_a}b.parentNode.removeChild(b)}if(ig_.ua){document.body.style.display="none";document.body.style.display=""}return a}
function ig_Hb(a){switch(a){case "titleclick":_IG_TriggerModuleEvent(this.b.id,a,this.e.href);_IG_TriggerEvent("module"+a,this.b.id,this.e.href);break;case "dragstart":case "dragend":_IG_TriggerDelayedModuleEvent(this.b.id,a);_IG_TriggerDelayedEvent("module"+a,this.b.id);break}}
function ig_ub(a,b){return function(){var c=ig_Kb(),d=ig_Jb(),e=d[1],f=4,g=0.05*c,h=e,j=a.offsetTop;if(a.lastMouseY<=g){j=a.offsetTop-f;h=e-f}else if(a.lastMouseY>=c-g){j=Math.min(b-a.offsetHeight,a.offsetTop+f);h=Math.min(b-c,e+f)}var i=h-e;if(i!=0){window.scrollBy(0,i);a.style.top=j+"px"}}}
function ig_Kb(){var a;a=window.innerHeight?window.innerHeight:document.documentElement&&document.documentElement.clientHeight?document.documentElement.clientHeight:document.body.offsetHeight;if(a<document.body.clientHeight)return a;return document.body.clientHeight}_IG_AddCustomEventHandler("initdrag",function(a,b){_IG_initDrag(a,b)});_exportSymbols("",["IG_DND",ig_]);window._IG_PU=function(){var a=ig_a,b;function c(d){if(!arguments.callee.calledOnce){var e={IG_PU_box:"div",IG_PU_iframe_cover:"iframe",IG_PU_bg:"div"};for(var f in e){var g=document.createElement(e[f]);g.id=f;g.style.display="none";document.body.insertBefore(g,document.body.firstChild)}arguments.callee.calledOnce=ig_a}return _gel(d)}return{open:function(d,e,f,g,h){a=typeof e=="string";var j=c("IG_PU_box");if(j&&j.style.display=="none"){f||(f=[_IG_PU_MakeDialogButton("Save"),_IG_PU_MakeDialogButton("Cancel")]);
var i=['<table class=dialog id=IG_PU_dlg cellspacing=0 cellpadding=0><tr><td><div class=outerborder><div class="border titlebar">',d,'</div><div class="border body" id=dialogcontent>',a?e:"",ig_Lb(f),"</div></td></tr></table>"].join("");ig_Mb(i,g,a?ig_b:e,h)}},openUrl:function(d,e,f,g,h,j,i){var k=_IG_PU_createSimpleTitle(d)+(e||""),l=['<div class=url><iframe id=popup_iframe style="width:',g,';height:0px;" src="',f,'" onload="_ResizeIframeHeight();" scrolling=no frameborder=0></iframe><div class=c></div>',
ig_Lb(h,"colored_background")].join("");window._IG_PU.open(k,l,[],j,i)},hide:function(d){var e=_gel("button_"+d);if(!(e&&e.firstChild&&e.firstChild.disabled)){c("IG_PU_box").style.display="none";c("IG_PU_iframe_cover").style.display="none";var f=c("IG_PU_bg");f.onclick="";f.style.height="";f.style.width="";if(!a){var g=_gel("dialogcontent").firstChild;d!=_DI_button_type.OK&&g.nodeName=="FORM"&&g.reset();setTimeout(function(){var i=_gel("popup_box_placeholder");i.parentNode.insertBefore(_gel("dialogcontent").firstChild,
i);i.parentNode.removeChild(i)},1000)}var h=_gel("popup_iframe"),j=h&&h.contentWindow.getPopupData?h.contentWindow.getPopupData():ig_b;_IG_RemoveEventHandler("resize",h?_ResizeIframeHeight:ig_4);_IG_RemoveDOMEventHandler(window,"scroll",ig_4);b(d,j)}},createSimpleTitle:function(d){return["<div class=popup_title>",d,'</div><div class=popup_title_buttons><a onclick="_IG_PU_hide(_DI_button_type.Close);" class=delbox  href="javascript:void(0)"></a></div><div class=c></div>'].join("")},findFocusable:function(d,
e,f){if(!d.disabled){var g=d.nodeName.toLowerCase();if(g=="input"||g=="button")return d;if(!f){if(g=="a"&&ig_Nb(d,"href"))return d;if(d.nodeType==1&&ig_Nb(d,"tabindex")&&d.tabIndex!=-1)return d}}if(!d.hasChildNodes())return ig_b;var h=d.childNodes;if(e)for(var j=0,i;i=h[j];j++){var k=ig_5(i,e,f);if(k)return k}else for(j=h.length-1;i=h[j];j--)if(k=ig_5(i,e,f))return k;return ig_b},makeDialogButton:function(d,e,f,g){var h=["<input type=button"];e&&h.push(' id="'+e+'"');f&&h.push(' class="'+f+'"');g&&
h.push(' onclick="'+g+'"');h.push(' value="',d,'"></input>');return h.join("")},disableHideForButton:function(d){var e=_gel("button_"+d);if(e)e.onclick=function(){}},createSimpleInputBox:function(d,e,f){return['<div class="popup_body thinpadding"><form onsubmit="_IG_PU_hide(_DI_button_type.OK); return false;"><table cellspacing=0 cellpadding=0 border=0><tr><td class=sidepadding>',_hesc(e),'</td><td class=sidepadding><input id="',_hesc(d),'" name="',_hesc(d),'" ','type=text size=45 value="'+_hesc(f)+
'"></td>',"</tr></table></form></div>"].join("")},hasAttr:function(d,e){if(d.getAttributeNode){var f=d.getAttributeNode(e);return f?f.specified:ig_c}return d.getAttribute(e)!=ig_b},limitFocus:function(d){d=d||window.event;var e=d.target||d.srcElement,f=d.keyCode||d.charCode||d.which;if(f==9){var g=ig_5(this,ig_a,ig_c);if(!g)return ig_a;var h=ig_5(this,ig_c,ig_c);if(e==g&&d.shiftKey&&!(d.ctrlKey||d.altKey)){h.focus();return ig_c}else if(e==h&&!(d.shiftKey||d.ctrlKey||d.altKey)){g.focus();return ig_c}}return ig_a},
buildButtons:function(d,e){if(!d||!d.length)return"";var f=['<div id=buttons class="button_background'];e&&f.push(" "+e);f.push('"><table class=buttontable cellspacing=0 cols=');f.push(d.length,"><tr>");for(var g=0;g<d.length;++g){f.push("<td align=center>");f.push('<span id="button_',g,'" ');f.push('onclick="_IG_PU_hide(',g,')">');f.push(d[g]);f.push("</span>");f.push("</td>")}f.push("</tr></table></div></div>");return f.join("")},showDialog:function(d,e,f,g){var h=3000,j=c("IG_PU_bg"),i=j.style;
i.zIndex=h;i.background="#000";ig_Ob(j,ig_a);i.position="absolute";j.onclick=function(){};i.display="none";i.left="0px";i.top="0px";var k=c("IG_PU_box"),l=c("IG_PU_iframe_cover");k.innerHTML=d;if(!a&&f){var o=document.createElement("div");o.id="popup_box_placeholder";o.style.display="none";f.parentNode.insertBefore(o,f);_gel("dialogcontent").insertBefore(f,_gel("dialogcontent").firstChild)}var p=k.style;p.position="absolute";p.zIndex=h+1;var q=l.style;q.position="absolute";p.visibility="hidden";p.display=
"block";ig_4();p.visibility="visible";q.display="";i.display="block";_IG_AddEventHandler("resize",_gel("popup_iframe")?_ResizeIframeHeight:ig_4);_IG_AddDOMEventHandler(window,"scroll",ig_4);_gel("IG_PU_dlg").onkeydown=ig_Pb;e=e||function(){};if(g&&g.length){for(var r=[],m=0;m<g.length;++m){var n=_gel(g[m]);if(n){r.push(g[m]);n.setAttribute("old_position",n.style.position);n.setAttribute("old_left",n.style.left);n.style.position="relative";n.style.left="-99999px"}}b=function(u,v){e(u,v);for(var w=
0;w<r.length;++w){var t=_gel(r[w]);if(t){t.style.position=t.getAttribute("old_position");t.style.left=t.getAttribute("old_left")}}}}else b=e;var s=ig_5(k,ig_a,ig_a);s&&s.focus()},position:function(){var d=c("IG_PU_box"),e=c("IG_PU_iframe_cover"),f=c("IG_PU_bg"),g=document.body.clientWidth,h=window.innerHeight;if(!h)h=document.documentElement.offsetHeight;var j=d.offsetHeight<h,i=d.style;if(d){var k=(g-d.offsetWidth)/2,l=Math.max((h-d.offsetHeight)/2+ig_K(),0);if(!j&&i.top)l=parseInt(i.top,10);i.left=
k+"px";i.top=l+"px";var o=e.style;o.left=k+"px";o.top=l+"px";o.width=d.offsetWidth+"px";o.height=d.offsetHeight+"px"}if(f){var p=parseInt(i.top,10)+d.offsetHeight,q=Math.max(ig_J(),h,p);f.style.height=q+"px";f.style.width=document.body.clientWidth+"px"}},toggleTransparency:function(d,e){var f=d.style;if("opacity"in f)f.opacity=e?0.5:1;else if("MozOpacity"in f)f.MozOpacity=e?0.5:1;else if("filter"in f)f.filter=e?"alpha(opacity=50)":"alpha(opacity=100)"},resizeIframeHeight:function(){var d=_gel("popup_iframe");
if(d){var e=d.style;e.height=ig_J(d.contentWindow.document.body)+"px";e.display="block";e.display=""}ig_4()}}}();
var _DI_button_type={Close:-1,OK:0,Cancel:1},_IG_PU_hide=window._IG_PU.hide,_IG_PU_open=window._IG_PU.open,_IG_PU_openURL=window._IG_PU.openUrl,_IG_PU_disable_hide_for_button=window._IG_PU.disableHideForButton,_IG_PU_MakeDialogButton=window._IG_PU.makeDialogButton,_ResizeIframeHeight=window._IG_PU.resizeIframeHeight,ig_Ob=window._IG_PU.toggleTransparency,_IG_PU_createSimpleTitle=window._IG_PU.createSimpleTitle,ig_5=window._IG_PU.findFocusable,ig_Nb=window._IG_PU.hasAttr,ig_Pb=window._IG_PU.limitFocus,
ig_Lb=window._IG_PU.buildButtons,ig_4=window._IG_PU.position,ig_Mb=window._IG_PU.showDialog;function _IG_PU_init(){}function _IG_PU_IGNORE(){};function _hide_sent_content_messages(){_gel("sent_content_msg").className="hidden_msg";_gel("sent_tab_box").className="hidden_msg_box";_gel("send_tab_error_box").className="hidden_msg_box";_gel("sent_gadget_box").className="hidden_msg_box"}var ig_6=ig_b;
function _share_gadget(a,b,c,d,e,f,g,h){if(d){_hide_sent_content_messages();if(!ig_6)ig_6=_gel("sent_gadget_box").innerHTML;_gel("sent_gadget_box").innerHTML=ig_6.replace("GADGET_NAME",_get_module_title(d))}if(g)var j="_gel('popup_iframe').contentWindow.prepareEmail(_gel('share_userprefs') ? _gel('share_userprefs').checked : false)";else j="_gel('popup_iframe').contentWindow.prepareEmail();";var i=['<input type="button" id="send_btn" disabled="true" onclick="'+j+'" value="'+e+'"></input>',_IG_PU_MakeDialogButton(f)],
k="titlebar userprefs userprefs_border",l=_get_userprefs_checkbox_html(g,h,k);_IG_PU_openURL(a,l,b,c,i,d?_finish_sharing_gadget:ig_b);_IG_PU_disable_hide_for_button(0)}
function _share_this_gadget(a,b,c,d){if(c){_hide_sent_content_messages();if(!ig_6)ig_6=_gel("sent_gadget_box").innerHTML;_gel("sent_gadget_box").innerHTML=ig_6.replace("GADGET_NAME",_get_module_title(c))}var e=d||function(){},f=function(g,h){e(g,h);c&&_finish_sharing_gadget(g)};_IG_PU_openURL('<img src="/ig/images/sharegadget.gif"> '+a,ig_b,b,"555px",ig_b,f);_IG_PU_disable_hide_for_button(0)}
function _share_tab_with_gadget_checkboxes(a,b,c,d,e,f,g){var h='<iframe id="popup_iframe" width="100%" height="0px" src="'+_hesc(b)+'" onload="_ResizeIframeHeight();" scrolling="no"></iframe>',j="_gel('popup_iframe').contentWindow.storeTabAndPrepareEmail(_find_unshared_gadgets(), _gel('share_userprefs') ? _gel('share_userprefs').checked : false);",i=['<input type="button" id="send_btn" disabled="true" onclick="'+_hesc(j)+'" value="'+_hesc(f)+'"></input>',_IG_PU_MakeDialogButton(g)];if(_uli){for(var k=
_get_all_modules(),l=Math.max(k.length*160,400),o=7,p=0,q=0;q<k.length;q++)if(k[q].length>p)p=k[q].length;var r=p>o&&c!="NO_TRANSLATION",m=[a];m.push('<form id="module_list">');m.push('<table class="titlebar module_list_table" ','cols="',k.length,'"',' width="',l,'px">');r?m.push('<tr class="zipped_modules" id="module_list_zipper">'):m.push('<tr class="unzipped_modules">');for(var n=0;n<k.length;n++){m.push('<td width="',100/k.length,'%" ','valign="top">');for(var s=0;s<k[n].length;s++){var u=_hesc(k[n][s].id.replace("m_",
"")),v=_hesc(_get_module_title(k[n][s]));m.push('<div class="module_item');s>=o&&r&&m.push(" extra_items");m.push('">');m.push('<input id="share_',u,'" type="checkbox"'," checked ></input>");m.push('<label for="share_',u,'">',v,"</label>");m.push("</div>")}m.push("</td>")}m.push("</tr>");if(r){m.push('<tr class="zipped_module_list">');m.push('<td id="show_all_modules" colspan="',k.length,'" style="font-size:80%;text-align:center;">');m.push('<a href="javascript:void(0);" id="zipper_text"',' onclick="_modules_zipper();">');
m.push(c,"</a>");m.push("</td></tr>")}m.push("</table>");m.push(_get_userprefs_checkbox_html(d,e,"userprefs"));m.push("</form>");_IG_PU_open(m.join(""),h,i);_IG_PU_disable_hide_for_button(0);_gel("dialogcontent").className+=" url";_gel("buttons").className+=" colored_background"}else{_IG_PU_open(a,h,i);_gel("buttons").className+=" colored_background"}}
function _show_shared_userprefs_alert(){if(_gel("share_userprefs").checked){_gel("share_userprefs_alert").style.display="block";_gel("popup_iframe").contentWindow.shouldShareUserprefs(ig_a)}else{_gel("share_userprefs_alert").style.display="none";_gel("popup_iframe").contentWindow.shouldShareUserprefs(ig_c)}}
function _get_userprefs_checkbox_html(a,b,c){var d=[];if(a&&a!=""){d.push('<div class="',c,'">');d.push('<input id="share_userprefs" type="checkbox"');b!=""&&d.push(' onclick="_show_shared_userprefs_alert();"');d.push("></input>");d.push('<label for="share_userprefs">',a,"</label>");b!=""&&d.push('<div class="userprefs_alert"',' id="share_userprefs_alert">',b,"</div>");d.push("</div>")}return d.join("")}
function _modules_zipper(){if(_gel("module_list_zipper").className=="zipped_modules"){_gel("module_list_zipper").className="unzipped_modules";_gel("show_all_modules").style.display="none"}_ResizeIframeHeight()}function _find_unshared_gadgets(){for(var a=_gel("module_list").elements,b=[],c=0;c<a.length;c++)ig_Qb(a[c])||(b[b.length]=a[c].id.replace("share_",""));return b}
function ig_Qb(a){if(a&&a.tagName=="INPUT"){var b=_gel("module_list_zipper"),c=b&&/unzipped_modules/.test(_gel("module_list_zipper").className),d=/extra_items/.test(a.parentNode.className),e=!b||c||!d;return a.checked&&e}return ig_c}function _finish_sharing_gadget(a){if(a==_DI_button_type.OK){_gel("sent_content_msg").className="msg";_gel("sent_tab_box").className="hidden_msg_box";_gel("send_tab_error_box").className="hidden_msg_box";_gel("sent_gadget_box").className="msg_box"}}
function _finish_sharing_tab(a){_gel("sent_content_msg").className="msg";_gel("sent_gadget_box").className="hidden_msg_box";if(a){_gel("sent_tab_box").className="msg_box";_gel("send_tab_error_box").className="hidden_msg_box"}else{_gel("send_tab_error_box").className="msg_box";_gel("sent_tab_box").className="hidden_msg_box"}};function ig_Rb(a){var b=_gel("mobile_screen");b.insertBefore(a,b.firstChild);a.style.display="block";var c=ig_Sb(a.id),d=_gel("m_"+c);_gel("added_m_"+c).style.display="";_gel("add_m_"+c).style.display="none";d.style.filter="alpha(opacity=30)";d.style.opacity=0.3;if(!ig_.ta)d.style.width="100%"}function _addToMobileDisplayAndLog(a){ig_Rb(a);ig_.Ca("add")}function _delFromMobileAndLog(a,b,c){ig_Tb(a,b,c);ig_.Ca("del")}
function ig_Tb(a){var b=_gel("mobile_m_"+a),c=_gel("m_"+a);b.style.display="none";if(c){c.style.filter="alpha(opacity=100)";c.style.opacity=1;var d=_gel("add_"+c.id),e=_gel("added_"+c.id);e.style.display="none";d.style.display=""}}function ig_Sb(a){if(a.indexOf("mobile")==0)return a.substring("mobile_m_".length);return a.substring("m_".length)}function ig_Ub(){for(var a=0;a<ig_.q.length;a++){ig_.q[a].P();ig_.q[a]=ig_b}ig_.q=ig_b}
ig_.hb=function(a){for(var b=0;b<ig_.q.length;b++){var c=ig_.q[b];c.b.pagePosLeft=ig_.k(c.b,ig_a);c.b.pagePosTop=ig_.k(c.b,ig_c)}for(var d=a.b.nextSibling;d;){d.pagePosTop-=a.b.offsetHeight;d=d.nextSibling}};ig_.Ca=function(a){for(var b="",c=_gel("mobile_screen"),d=0;d<c.childNodes.length;d++){var e=c.childNodes[d];if(e.style.display!="none"){b+=b!=""?":":"";b+=e.id.substring(9)}}_xsetp("mobile_mp="+_esc(b)+"&action="+_esc(a))};
function ig_Vb(a){this._dragStart=ig_Wb;this._drag=ig_Xb;this._dragEnd=ig_Yb;this.P=ig_Ib;this.ia=ig_Gb;this.o=ig_c;this.b=a;this.b.style.cursor="move";this.j=_gel(a.id+"_h");this.Oa=_gel(a.id+"_b");this.j&&ig_3.init(this.j,this.b);this.Oa&&ig_3.init(this.Oa,this.b);this.b.onDragStart=ig_.p(this,"_dragStart");this.b.onDrag=ig_.p(this,"_drag");this.b.onDragEnd=ig_.p(this,"_dragEnd")}
function ig_Wb(){ig_.hb(this);this.origNextSibling=this.b.nextSibling;var a=ig_.G(),b=this.b.offsetHeight;if(ig_.ta)b-=parseInt(a.style.borderTopWidth,10)*2;a.className="";var c=this.b.offsetWidth,d=ig_.k(this.b,ig_a),e=ig_.k(this.b,ig_c);ig_.ob();this.b.style.width=c+"px";a.style.height=b+"px";this.b.parentNode.insertBefore(a,this.b.nextSibling);this.b.style.position="absolute";this.b.style.zIndex=100;this.b.style.left=d+"px";this.b.style.top=e+"px";ig_.qb();ig_.Na(this);return this.o=ig_c}
function ig_Xb(a,b){if(!this.o){this.b.style.filter="alpha(opacity=70)";this.b.style.opacity=0.7;this.o=ig_a}for(var c=ig_b,d=100000000,e=0;e<ig_.q.length;e++){var f=ig_.q[e],g=Math.sqrt(Math.pow(a-f.b.pagePosLeft,2)+Math.pow(b-f.b.pagePosTop,2));if(!(f==this))if(!isNaN(g))if(g<d){d=g;c=f}}var h=ig_.G();h.className="";if(c!=ig_b&&h.nextSibling!=c.b){c.b.parentNode.insertBefore(h,c.b);if(ig_.ua){document.body.style.display="none";document.body.style.display=""}}}
function ig_Yb(){ig_.Ba();this.ia()&&ig_.Ca("move");return ig_a}var _IG_initMobileDrag=function(a){ig_.K=a;ig_.q=[];for(var b=0,c=_gel("mobile_screen").childNodes,d=0;d<c.length;d++){var e=c[d];if(e.tagName=="DIV"){ig_Zb(e)&&ig__b(e);ig_.q[b]=new ig_Vb(e);b++}}_IG_AddEventHandler("unload",ig_Ub)};function ig_Zb(a){var b=_gel(a.id+"_h");if(b){var c=_gel(a.id+"_h").innerHTML;if(c.indexOf("Google Reader")>=0)return ig_a}}
function ig__b(a){for(var b=_gel(a.id+"_b"),c=0;c<b.childNodes.length;c++){var d=b.childNodes[c];if(d.tagName=="TABLE")d.className="mmc"}};function _START_TEMPLATE_SECTION(){}function _END_TEMPLATE_SECTION(){}function _TEMPLATE_VARIABLE(){}function _INLINE_TEMPLATE_SECTION(){}function _PARENS(){};var ig_7={Ma:-1,Ha:1,Ia:0},ig_8={Pa:document.location.hostname,gb:document.location.pathname,ra:ig_7.Ma};function _setHomepage(a,b){var c=_gel("hp_url").innerHTML;a.style.behavior="url(#default#homepage)";a.setHomePage(c);_sendx("/ig/ui?action=sethomepage&url="+_esc(c)+"&type="+b+"&confirmed="+(_IGoogleIsHomepage()?1:0))}
function _IGoogleIsHomepage(){if(ig_8.ra==ig_7.Ma)ig_8.ra=_verifyIsIGoogleHomePage()?ig_7.Ha:ig_7.Ia;switch(ig_8.ra){case ig_7.Ha:return ig_a;case ig_7.Ia:return ig_c;default:return ig_c}}function ig_0b(a,b){a=a.replace(/\/$/,"");var c=["http://"+a+"/ig","http://"+a+"/ig?hl="+b,"http://"+a+"/ig?refresh=1","http://"+a+"/ig?hl="+b+"&refresh=1"];return c}function ig_1b(){var a=ig_8.Pa.replace(/\/$/,""),b=["http://"+a,"http://"+a+"/","http://"+a+"/webhp"];return b}
function _verifyIsIGoogleHomePage(){var a=_gel("shp"),b=_gel("hp_url").innerHTML;if(a.isHomePage(b)){ig_9("homepage_url",b);return ig_a}var c=_gel("shp_host"),d=_gel("shp_language");if(c&&d){var e=c.innerHTML,f=d.innerHTML;if(e&&f)for(var g=ig_0b(e,f),h=0;h<g.length;++h)if(a.isHomePage(g[h])){ig_9("igoogle",g[h]);return ig_a}}if(ig_2b()){g=ig_1b();for(h=0;h<g.length;++h)if(a.isHomePage(g[h])){ig_9("classic_google",g[h]);return ig_a}}return ig_c}
function ig_9(a,b){(new Date).getUTCMilliseconds()%100==0&&_sendx("/ig/ui?action=verifyishomepage&url="+_esc(b)+"&verify_source="+a)}function _maybeShowSetHPMsg(){if(!_IGoogleIsHomepage()){_gel("set_homepage_msg").style.display="inline";if(_gel("new_user_demo"))_gel("new_user_demo").style.display="none"}}function _hideSetHPMsg(){if(_gel("set_homepage_msg"))_gel("set_homepage_msg").style.display="none";if(_gel("new_user_demo"))_gel("new_user_demo").style.display="block"}
function _iGoogleRejectedAsHomepage(){if(_gel("set_homepage_msg"))_gel("set_homepage_msg").style.display="none";if(_gel("new_user_demo"))_gel("new_user_demo").style.display="block";if(_gel("set_homepage_footer"))_gel("set_homepage_footer").style.display="inline"}function _maybeShowSetHPFooter(){if(!_IGoogleIsHomepage()&&!_gel("set_homepage_msg"))_gel("set_homepage_footer").style.display="inline"}function ig_2b(){var a=ig_8.Pa.indexOf("www.google.")==0,b=ig_8.gb.indexOf("/ig")==0;return a&&!b};function _delpromobox(){_xsetp("hp=0");var a=_gel("promobox");a.parentNode.removeChild(a);return ig_c}function _delmessage(){_xsetp("gm=0");var a=_gel("googlemessage");a.parentNode.removeChild(a);return ig_c}function _delpromomod(){_xsetp("pm=0");var a=_gel("promomod");a.parentNode.removeChild(a);return ig_c};var ig_$=function(){},_IG_ViewType=ig_$,_IG_GetSupportedViews=ig_$,_IG_NavigateToGadget=ig_$,_IG_GetCurrentView=ig_$,_IG_GetViewParams=ig_$,_IG_is_maximized_module=function(){return ig_c},_IFPC_NavigateTo=function(){},_IG_maximize_persistent_module=function(){},_IG_toggle_view=ig_$,_IG_maximize_view=ig_$,_IG_minimize_view=ig_$,_IG_restore_view=ig_$,_IG_iFrameTransitionStrategy=function(){},_IG_inlinedTransitionStrategy=function(){},_IG_scaleInlinedTransitionStrategy=function(){},_IG_noMaxSupportTransitionStrategy=
function(){},_IG_noMaxSupportResizeIframe=function(){},ig_3b=new function DummyV1ViewManager(){};ig_3b.isModuleMaximized=function(){return ig_c};_exportSymbols("gadgets.views",["ViewType",_IG_ViewType,"getSupportedViews",_IG_GetSupportedViews,"requestNavigateTo",_IG_NavigateToGadget,"getCurrentView",_IG_GetCurrentView,"getParams",_IG_GetViewParams]);_exportClass("gadgets.views","ViewManager",["isModuleMaximized",ig_3b.isModuleMaximized]);
